Repository tc39/ecma262, pull requests merged in 2018-04, with the labels that each got.

#1161 Misc Editorial
  spec.html
Labels: editorial change

#1173 Editorial: Move AsyncFunctionCreate into 9.2 ECMAScript Function
  spec.html
Labels: editorial change

#1153 Editorial: Move global object dfn to the Global Object section
  spec.html
Labels: editorial change

#1116 Editorial: Fix typo
  spec.html
Labels: editorial change

#1096 Editorial: add a SetFunctionLength abstract operation
  spec.html
Labels: editorial change

#1108 Editorial: Added missing sentence periods
  spec.html
Labels: editorial change

#1123 Normative: FlagText allows s
  spec.html
Labels: normative change, spec bug

#1112 Layering: Check for the correct owner in DetachArrayBuffer
  spec.html
Labels: has consensus

#1182 Misc Editorial
  spec.html
Labels: editorial change
