Repository tc39/ecma262, pull requests merged in 2018-07, with the labels that each got.

#1256 Misc Editorial
  spec.html
Labels: editorial change

#1249 Remove bogus assertion in GetModuleNamespace.
  spec.html
Labels: normative change, spec bug

#1248 Editorial: Simplify %AsyncFromSyncIteratorPrototype% methods
  spec.html
Labels: editorial change

#1259 Editorial: remove trailing space
  spec.html
Labels: editorial change

#1163 Normative: specify RequireObjectCoercible as first step in destructuring assignment semantics
  spec.html
Labels: has tests, normative change, spec bug, web reality

#1188 Extend ECMA-262 syntax into a superset of JSON
  spec.html
Labels: has tests, normative change, proposal

#1207 Evaluate this binding first in SuperProperty
  spec.html
Labels: has consensus, has tests, normative change, web reality

#1262 Editorial: create addIterableFromEntries abstract operation
  spec.html
Labels: editorial change
