Repository tc39/ecma262, pull requests merged in 2018-05, with the labels that each got.

#1141 Editorial: fix section IDs for some async generator sections.
  spec.html
Labels: editorial change, needs-spec-draft-integration, rendering bug

#1102 Normative: add RegExp lookbehind to annex-B
  spec.html
Labels: has consensus, has tests, needs-spec-draft-integration, normative change, spec bug, web reality

#1187 Editorial: clarify that [[Construct]] implies [[Call]]
  spec.html
Labels: editorial change

#1186 Editorial: Fix incorrect [[Status]] value from "errored" to "evaluated"
  spec.html
Labels: editorial change

#1179 Editorial: specify Date.parse cannot return an abrupt completion
  spec.html
Labels: editorial change

#1125 Editorial: use <ul> to list characteristics of intrinsics
  spec.html
Labels: editorial change
