Repository tc39/ecma262, pull requests merged in 2018-08, with the labels that each got.

#1132 Restore early SyntaxError for strict mode assignment to eval/arguments
  spec.html
Labels: has tests, normative change, web reality

#1144 Normative: Cleanup Time Values and Time Range
  spec.html
Labels: has consensus, has tests, normative change

#1272 Editorial: Add %JSONStringify% intrinsic object
  spec.html
Labels: editorial change

#1220 Renames Atomics.wake => Atomics.notify
  spec.html
Labels: has consensus, has tests, normative change

#1269 Date.prototype.toString is not generic
  spec.html
Labels: editorial change, spec bug, web reality

#1252 Editorial: Update date-time format language
  spec.html
Labels: editorial change

#1279 Editorial: fix a few variable names
  spec.html
Labels: editorial change

#1239 Editorial: "length" should be used consistently
  spec.html
Labels: editorial change

#1162 Editorial: ensure spaces around binary operators
  spec.html
Labels: editorial change

#1146 Editorial: refactor PerformPromiseThen to allow no capability
  spec.html
Labels: editorial change

#1226 Editorial: [[Extensible]] description should reference EIM invariants
  spec.html
Labels: editorial change

#1285 Editorial: Remove some extraneous "result of performing"
  spec.html
Labels: editorial change

#1286 Normative: Use GetValue to evaluate class heritage.
  spec.html
Labels: normative change, spec bug

#1127 Normative: Strengthen Atomics.wait/notify synchronization to the level of other Atomics operations
  spec.html
Labels: has consensus, normative change, spec bug
