Repository tc39/ecma262, pull requests merged in 2019-10, with the labels that each got.

#1670 Editorial: Fix null [[ScriptOrModule]] of function declarations in modules
  spec.html
Labels: spec bug

#1679 Meta: Corrected typo in contributing.md
  CONTRIBUTING.md
Labels: meta

#1712 Normative: Fix bogus assert in NotifyWaiter
  spec.html
Labels: spec bug

#1124 Normative: Remove ToUint32 from array literal evaluation
  spec.html
Labels: has consensus, normative change

#1714 Editorial: quick fixes
  spec.html
Labels: editorial change

#1692 Strengthen Atomics critical section to imply synchronizes-with
  spec.html
Labels: has consensus, normative change, spec bug

#702 Normative: add `globalThis`
  spec.html
Labels: has stage 4, normative change, proposal

#1174 Normative: Add `export * as ns from "mod”` to Export production and Module Semantic
  spec.html
Labels: has consensus, has tests, normative change

#1718 Update .gitignore
  .gitignore
Labels: invalid, meta

#1716 Normative: make String.prototype.matchAll throw for non-global regular expressions
  spec.html
Labels: has consensus, has tests, normative change

#1676 Editorial: use `! CreateDataPropertyOrThrow` instead of `CreateDataProperty` and an assert
  spec.html
Labels: editorial change

#1010 Resolve #1007 - say what the draft reprsents
  spec.html
Labels: editorial change

#1635 Editorial: fix and improve definition of %ThrowTypeError%
  spec.html
Labels: editorial change

#1720 Editorial: fix intrinsic notation from previous PRs
  spec.html
Labels: editorial change

#1302 Editorial: Quote properties across the board.
  spec.html
Labels: editorial change

#1684 Editorial: Improve %JSONStringify% intrinsic definition
  spec.html
Labels: editorial change

#1641 Editorial: Rephrase "ListIterator next"
  spec.html
Labels: editorial change

#1526 Editorial: Improve note on forcing string comparison
  spec.html
Labels: editorial change

#1722 Editorial: quick fixes for recent merges
  spec.html
Labels: editorial change

#1731 [meta] use an HTML comment to avoid auto-dfn-linking
  spec.html
Labels: meta

#1325 Editorial: Better relate ECMAScript time values to POSIX and UTC
  spec.html
Labels: editorial change

#1728 Editorial: Reference DecimalDigit rather than duplicating its RHS
  spec.html
Labels: editorial change

#1726 replace es-discuss link in CONTRIBUTING with discourse link
  CONTRIBUTING.md
Labels: meta

#1284 Editorial: Correct and make readable for-in/of/await-of static semantics
  spec.html
Labels: editorial change

#1725 Editorial: Use tildes for spec-internal values wherever possible.
  spec.html
Labels: editorial change

#1734 Editorial: tweaks relating to the TypedArray Constructors table
  spec.html
Labels: editorial change

#1724 Editorial: Use consistent notation for code points.
  spec.html
Labels: editorial change

#1736 Editorial: Stylize "this object" consistently.
  spec.html
Labels: editorial change

#1694 Editorial: Remove the |Keyword| nonterminal
  spec.html
Labels: editorial change

#1685 Editorial: remove context copy from AsyncFunctionStart
  spec.html
Labels: editorial change

#1743 reword only use of "_x_'s Y component"
  spec.html
Labels: editorial change

#1740 rename cxt/ctx variables to context
  spec.html
Labels: editorial change

#1746 find Directive Prologue in appropriate node in IsStrict/ContainsUsestrict
  spec.html
Labels: editorial change, spec bug

#1748 Revert "Editorial: remove context copy from AsyncFunctionStart (#1685)"
  spec.html
Labels: editorial change, spec bug

#1745 add missing ContainsUseStrict definition for AsyncConciseBody
  spec.html
Labels: normative change, spec bug

#1698 Editorial: add missing Annex E entries
  spec.html
Labels: editorial change

#1733 Editorial: Stylize strings as values.
  spec.html
Labels: editorial change

#1750 Markup: fix a malformed <emu-xref> tag
  spec.html
Labels: editorial change, spec bug

#1546 Editorial: simplifications around [[FunctionKind]] and _functionKind_
  spec.html
Labels: editorial change

#1756 Normative: Restore BigInt.prototype.toJSON
  spec.html
Labels: normative change, spec bug

#1753 Normative: Make BigInt a global
  spec.html
Labels: normative change, spec bug

#1762 Editorial: quick fix re insertion of global BigInt
  spec.html
Labels: editorial change

#1752 Editorial: Refactor index checking for Integer-Indexed exotic objects
  spec.html
Labels: editorial change
