Repository tc39/ecma262, pull requests merged in 2019-01, with the labels that each got.

#1381 Editorial: Fix formatting of grammar productions ending in html entities
  package.json
Labels: rendering bug

#1328 Editorial: Add explicit Return to Await
  spec.html
Labels: editorial change

#1416 Editorial: Tweak String.prototype.repeat
  spec.html
Labels: editorial change

#1330 Editorial: add ‘!’ to CreateDataPropertyOrThrow calls in PropertyDefinitionEvaluation
  spec.html
Labels: editorial change

#1340 [Normative] Make Array.prototype.sort stable
  spec.html
Labels: has consensus, has tests, normative change, web reality
