Repository tc39/ecma262, pull requests merged in 2019-09, with the labels that each got.

#1636 Editorial: misc fixes
  spec.html
Labels: editorial change, spec bug

#1160 Editorial: LocalTZA input specification
  spec.html
Labels: editorial change

#1648 Editorial: Fixed typo in spec
  spec.html
Labels: editorial change, spec bug

#1695 Editorial: Define critical section
  spec.html
Labels: editorial change

#1696 Editorial: Spell out fairness requirements of EnterCriticalSection
  spec.html
Labels: editorial change

#1503 Editorial: ES 2020 is the eleventh edition
  spec.html
Labels: editorial change, spec bug

#1515 Normative: Add new BigInt primitive
  spec.html
Labels: has stage 4, has tests, normative change, proposal

#1583 Normative: Add Promise.allSettled()
  spec.html
Labels: has stage 4, has tests, proposal

#1704 Editorial: quick fixes for recently-merged commits
  spec.html
Labels: editorial change, spec bug

#1705 Editorial: more quick fixes
  spec.html
Labels: editorial change

#1708 Editorial: Changing 'SetViewValue' to use 'ToNumber' instead of 'ToInteger'
  spec.html
Labels: normative change, spec bug
