Repository tc39/ecma262, pull requests merged in 2019-11, with the labels that each got.

#1769 Editorial: Add BigInt to the list of primitive values
  spec.html
Labels: editorial change, spec bug

#1580 Editorial: Move ToObject out of GetSubstitution
  spec.html
Labels: editorial change

#1479 Normative: CreateDynamicFunction early concatenates bodyText
  spec.html
Labels: has consensus, has tests, normative change, web reality

#1523 Editorial: Delete unwanted use of "implementation-defined"
  spec.html
Labels: editorial change

#1562 Editorial: Merge FunctionAllocate and FunctionInitialize
  spec.html
Labels: editorial change

#1464 Editorial: correctly determine flags for static RegExp parsing
  spec.html
Labels: editorial change

#1778 Editorial: quick fixes
  spec.html
Labels: editorial change

#1411 Editorial: Treat not present parameters as `undefined`
  spec.html
Labels: editorial change

#1783 Editorial: Fix dangling "Otherwise" step
  spec.html
Labels: editorial change, spec bug

#1579 Editorial: Name internal slots of iterators consistently
  spec.html
Labels: editorial change

#1608 Normative: IsSimpleParameterList is false for standalone rest parameters
  spec.html
Labels: normative change, spec bug

#1766 Normative: Properly handle Number(BigInt)
  spec.html
Labels: normative change, spec bug

#1773 Editorial: Add BigInt to the list of reference base value types and the language types intro text
  spec.html
Labels: editorial change, spec bug

#1702 Editorial: simplify ArraySetLength truncation
  spec.html
Labels: editorial change

#1653 Editorial: Remove stray reference to ModuleDeclarationEnvironmentSetup.
  spec.html
Labels: editorial change, spec bug

#1652 Editorial: Simplify AssignmentTargetType values.
  spec.html
Labels: editorial change

#1567 Editorial: Extract IsNonNegativeInteger abstract op
  spec.html
Labels: editorial change

#1790 Editorial: Fix Elymiac row markup in scripts table
  table-unicode-script-values.html
Labels: editorial change, rendering bug

#1183 Editorial: replace obj.[[Get]](j) with Get(obj, j)
  spec.html
Labels: editorial change
