Repository tc39/ecma262, pull requests merged in 2019-04, with the labels that each got.

#1356 Editorial: fix assertion in IteratorBindingInitialization
  spec.html
Labels: editorial change, spec bug

#1470 Editorial: Handle abrupt completion in AsyncFromSyncIteratorContinuation
  spec.html
Labels: editorial change, spec bug

#1317 Editorial: Update date-time format language
  spec.html
Labels: editorial change

#1352 Editorial: Fix a word choice typo in intro text
  spec.html
Labels: editorial change

#1361 Editorial: Use [[StringData]] to identify strings in %Object_toString%
  spec.html
Labels: editorial change

#1373 Editorial: add RequireInternalSlot abstract operation
  spec.html
Labels: editorial change

#1382 Editorial: Refactor GetExportedNames() and ResolveExport() calls
  spec.html
Labels: editorial change

#1387 Editorial: Clarify IEEE 754-2008 terminology
  spec.html
Labels: editorial change

#1401 Editorial: Clarify internal slots during object creation
  spec.html
Labels: editorial change

#1441 Normative: Remove implementation-defined typeof behavior
  spec.html
Labels: has consensus, normative change

#1449 meta: add issue templates
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-feature-request.md
Labels: meta

#1454 Editorial: Add missing <i> to IteratorResult interface
  spec.html
Labels: editorial change

#1468 Normative: Update Unicode property lists per Unicode v12
  table-unicode-script-values.html
Labels: has tests, normative change, unicode

#1471 Editorial: Grammar "so has the features..." -> "so have the features..."
  spec.html
Labels: editorial change

#1480 Normative: add `String.prototype.matchAll`/`Symbol.matchAll`
  spec.html
Labels: has stage 4, has tests, normative change, proposal

#1483 Editorial: Consistently represent JavaScript code
  spec.html
Labels: editorial change

#1486 Editorial: Don't read the [[Status]] of non-cyclic modules
  spec.html
Labels: spec bug

#1496 Fix typo (DFSAncestoreIndex -> DFSAncestorIndex)
  spec.html
Labels: editorial change

#1456 Misc Editorial
  spec.html
Labels: editorial change

#1499 Editorial: Introduce StringPad operation backing padStart and padEnd
  spec.html
Labels: editorial change

#1414 Editorial: Remove empty lists from Call arguments
  spec.html
Labels: editorial change

#1494 Meta: use discourse link in community box
  spec.html
Labels: meta

#1407 Normative: Require at least four digits in string representations of negative years
  spec.html
Labels: has consensus, has tests, normative change

#1137 Editorial: clarify when early errors for functions apply
  spec.html
Labels: editorial change, has consensus

#1410 Editorial: Use IsExtensible abstract op
  spec.html
Labels: editorial change

#1500 Meta: Improve the explanation of normative changes
  CONTRIBUTING.md
Labels: meta

#1513 Editorial: replace `lookahead ∉ { ele }` with `lookahead ≠ ele`
  spec.html
Labels: editorial change

#1516 Editorial: Remove unnecessary steps before NewPromiseCapability
  spec.html
Labels: editorial change
