Repository tc39/ecma262, pull requests merged in 2019-08, with the labels that each got.

#1638 fix link to TC39 meetings
  CONTRIBUTING.md
Labels: meta

#1376 Editorial: define and use improved intrinsics notation
  spec.html
Labels: editorial change

#1539 Normative: Disallow internal methods returning continue|break|return
  spec.html
Labels: has consensus, normative change

#1645 Normative: change idempotency for HostImportModuleDynamically
  spec.html
Labels: has consensus, has tests, normative change
