Repository tc39/ecma262, pull requests merged in 2019-02, with the labels that each got.

#1379 Editorial: fix type of ExportEntry Record [[ExportName]]
  spec.html
Labels: spec bug

#1433 [Normative] Make %TypedArray%.prototype.sort stable
  spec.html
Labels: has consensus, has tests, normative change

#1372 Add "name" property for classes as part of ClassDefinitionEvaluation
  spec.html
Labels: has consensus, has tests, normative change

#1393 Normative: Treat IterationStatements uniformly in Annex B.3.5.
  spec.html
Labels: has consensus, has tests, normative change

#1445 Meta: pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: meta

#1346 add Symbol.prototype.description getter
  spec.html
Labels: es2019, has stage 4, normative change, proposal

#1274 Normative: add `Object.fromEntries`
  spec.html
Labels: es2019, has stage 4, has tests, normative change, proposal

#1275 Normative: Add String.prototype.{trimStart/trimEnd} (+ trimLeft/trimRight)
  spec.html
Labels: es2019, has stage 4, has tests, normative change, proposal, web reality

#1378 Normative: LeftHandSideExpression -> UnaryExpression in Static Semantics: Early Errors
  spec.html
Labels: es2019, spec bug

#1396 Normative: Prevent JSON.stringify from returning ill-formed Unicode strings
  spec.html
Labels: es2019, has stage 4, normative change, proposal

#697 Normative: make Function.prototype.toString forward-compatible and fully defined
  spec.html
Labels: es2019, has stage 4, normative change, proposal

#1311 Layering: Enable cyclic dependencies with non-STMR module types
  spec.html
Labels: es2019, has consensus

#1368 Editorial: Add "async generator" to [[FunctionKind]] description
  spec.html
Labels: editorial change, es2019, spec bug

#1431 Editorial: Evaluate Disjunction :: Alternative with argument direction
  spec.html
Labels: es2019, spec bug

#1250 Normative: Reduce the number of ticks in async/await
  spec.html
Labels: es2019, has consensus, has tests, normative change

#1309 add Array.prototype.flatMap and Array.prototype.flat
  spec.html
Labels: es2019, has stage 4, normative change, proposal

#1300 Misc Editorial
  spec.html
Labels: editorial change, es2019

#1353 Fix indentation of the "Valid Chosen Reads" and "Coherent Reads"
  spec.html
Labels: es2019, normative change, spec bug

#1355 Editorial: fix a misused completion
  spec.html
Labels: editorial change, es2019, spec bug
