Repository tc39/ecma262, pull requests merged in 2019-07, with the labels that each got.

#1135 Editorial: Explicitly note mathematical values
  spec.html
Labels: editorial change

#1596 Editorial: misc
  spec.html
Labels: editorial change

#1602 Editorial: use `TrimString` in `parseFloat` and `parseInt`
  spec.html
Labels: editorial change

#1603 Editorial: use "be the *this* value" over "be *this* value"
  spec.html
Labels: editorial change

#1629 Editorial: '_trimmedString_' -> '_S_' in parseInt
  spec.html
Labels: editorial change, spec bug

#1625 Editorial: Added %RegExpStringIteratorPrototype% to well know Intrinsic objects table
  spec.html
Labels: editorial change, spec bug

#1568 Editorial: Correct the alt text of an image
  spec.html
Labels: editorial change

#1569 Normative: set [[SourceText]] in NamedEvaluation of ClassExpression
  spec.html
Labels: normative change, spec bug

#1571 Editorial: normalize wording used to apply syntax-directed operations
  spec.html
Labels: editorial change

#1574 Editorial: align formatting of metadata block
  spec.html
Labels: editorial change

#1582 Editorial: Fix typo: "module" -> "script"
  spec.html
Labels: editorial change

#1592 Editorial: Fix misformatted occurences of things that are "string values"
  spec.html
Labels: editorial change

#1601 Editorial: "_@@toStringTag_" -> "@@toStringTag" in %RegExpStringIteratorPrototype%
  spec.html
Labels: editorial change

#1604 Editorial: Replace usages of "add" and "subtract" with "set"
  spec.html
Labels: editorial change

#1607 Editorial: Add ! and ? before CreateBuiltinFunction and CreateArrayFromList
  spec.html
Labels: editorial change

#1613 Editorial: Some small formatting tweaks
  spec.html
Labels: editorial change

#1614 Editorial: Tweak ValidateAndApplyPropertyDescriptor
  spec.html
Labels: editorial change

#1615 Editorial: Add note on [[Delete]] in InternalizeJSONProperty
  spec.html
Labels: editorial change

#1616 Editorial: Define + use LengthOfArrayLike operation
  spec.html
Labels: editorial change

#1620 Editorial: `FlattenIntoArray`: add assertions
  spec.html
Labels: editorial change

#1622 Editorial: Use `!` on calls to `ToBoolean`
  spec.html
Labels: completion records, editorial change

#1626 Editorial: fix capitalization of "RegExp String Iterator"
  spec.html
Labels: editorial change

#1627 Meta: Refactor package.json scripts to use prebuild.
  package.json
Labels: meta

#1631 Editorial: Fixed typo in Shared Memory Guidelines note
  spec.html
Labels: editorial change

#1633 Meta: Add Stage 1 proposals list
  README.md
Labels: meta

#1634 Editorial: `parseFloat`/`parseInt`: fix unintentional normative change from #1629
  spec.html
Labels: spec bug
