Repository tc39/ecma262, pull requests merged in 2020-02, with the labels that each got.

#1552 Editorial: Introduce abstract ops UTF16Encode + UTF16DecodeString
  spec.html
Labels: editorial change

#1832 Meta: Update "To make a pull request" wording
  CONTRIBUTING.md
Labels: meta

#1856 Editorial: Unify spelling of 'behaviour'.
  spec.html
Labels: editorial change

#1460 Editorial: clarify ordinary and exotic object definitions and creation
  spec.html
Labels: editorial change

#1770 Editorial: Update IEEE 754 standard version
  spec.html
Labels: editorial change

#1827 Normative: ToInteger normalizes `-0` to `+0`
  spec.html
Labels: has consensus, has tests, normative change

#1547 Editorial: fix inconsistency re type of [[SourceText]]
  spec.html
Labels: editorial change, spec bug

#1775 Normative: Make super() throw after evaluating args
  spec.html
Labels: has consensus, has tests, normative change

#1864 Editorial: add missing argument to two CreateImmutableBinding calls
  spec.html
Labels: editorial change, spec bug

#1871 Normative: `ToInteger`: fix spec bug from #1827 that allows (-1,0) to produce `-0`
  spec.html
Labels: normative change, spec bug

#1862 Editorial: make callers of SV consistent
  spec.html
Labels: editorial change

#1787 Editorial: quick fixes for recent merges
  spec.html
Labels: editorial change

#1797 Editorial: remove AssertionTester from RexExp semantics
  spec.html
Labels: editorial change, spec bug

#1301 Normative: plug some holes in the coverage of syntax-directed operations
  spec.html
Labels: normative change, spec bug

#1830 Editorial: Update About this Specification wording
  spec.html
Labels: editorial change

#1808 Editorial: Improve readability in 11.10.
  spec.html
Labels: editorial change

#1658 Normative: Add two missing Early Error rules for productions covering an AssignmentPattern
  spec.html
Labels: normative change, spec bug

#1877 Editorial: supply args to IteratorBindingInitialization
  spec.html
Labels: editorial change, spec bug

#1879 Editorial: Update InternalizeJSONProperty to accept reviver explicitly
  spec.html
Labels: editorial change
