Repository tc39/ecma262, pull requests merged in 2020-10, with the labels that each got.

#2082 Editorial: move CreateRegExpStringIterator
  spec.html
Labels: editorial change

#1966 Editorial: Unambiguous grammar for IfStatement
  spec.html
Labels: editorial change

#2036 Editorial: Intrinsic %ArrayIterator% doesn’t exist
  spec.html
Labels: editorial change, spec bug

#2110 Editorial: Remove "Runtime Semantics" prefix from abstract operations
  spec.html
Labels: editorial change

#2120 Normative: explicitly specify order of operations in MakeTime
  spec.html
Labels: has consensus, has tests, spec bug

#2153 Editorial: Clarify that "length" value of built-in functions is non-negative
  spec.html
Labels: editorial change

#2182 Editorial: normalise date formatting/punctuation
  spec.html
Labels: editorial change

#2199 Editorial: clarify B.1.4.1, B.3.3.4, and B.3.3.5; other minor markup
  spec.html
Labels: editorial change

#2177 Editorial: replace some more internal usage of strings with spec enums
  spec.html
Labels: editorial change

#2142 Editorial: normalisation around List construction
  spec.html
Labels: editorial change

#2201 Editorial: normalise phrasing used to create Lists
  spec.html
Labels: editorial change

#2202 Editorial: reference %Array.prototype.sort% when sorting Lists
  spec.html
Labels: editorial change

#2007 Editorial: Make numeric values and operations default to mathematical values
  spec.html
Labels: editorial change

#2204 Meta: bump ecmarkup to 4.2.0
  package-lock.json
  package.json
Labels: meta

#2176 Editorial: Rewrite overloaded functions so each has a single definition
  spec.html
Labels: editorial change

#2132 Editorial: Add explicit early errors for (n)octal escape in directive prologue
  spec.html
Labels: editorial change

#2164 Normative: Align detached buffer semantics with web reality
  spec.html
Labels: has consensus, has tests, normative change, web reality

#2084 Editorial: Remove Formal[Rest]Parameter from IteratorBindingInitialization
  spec.html
Labels: editorial change

#2085 Editorial: Make Reference type a Record value
  spec.html
Labels: editorial change
