Repository tc39/ecma262, pull requests merged in 2020-12, with the labels that each got.

#2237 Meta: bump ecmarkup to 4.2.3
  package-lock.json
  package.json
Labels: meta

#1937 Editorial: Remove [[HomeObject]] from function Environments
  spec.html
Labels: editorial change

#2013 Editorial: Extract operation ParseText
  spec.html
Labels: editorial change

#2228 Editorial: Swap 2 alternatives of Term in Annex B
  spec.html
Labels: editorial change, spec bug

#2235 Editorial: Fix bug in Annex B defn of AtomEscape
  spec.html
Labels: editorial change, spec bug

#2224 Editorial: Resolve the 'dangling else' in Annex B.3.4 as in PR #1966
  spec.html
Labels: editorial change, ready to merge

#2207 Normative: IsDetachedBuffer should be checked before accessing [[ArrayLength]]
  spec.html
Labels: normative change, ready to merge, spec bug

#2215 Normative: add normative optional styling css override
  spec.html
Labels: normative change, ready to merge, spec bug

#2242 Editorial: put underscores around alias name
  spec.html
Labels: editorial change, ready to merge

#2244 Editorial: fix type in preamble of EvaluateCall
  spec.html
Labels: editorial change, ready to merge, spec bug

#2219 Editorial: Simplify Promise.all and Promise.any
  spec.html
Labels: ready to merge

#2239 Meta: Add link to tc39/template-for-proposals
  CONTRIBUTING.md
Labels: meta, ready to merge

#1994 Editorial: Standardize preambles for internal methods and concrete methods
  spec.html
Labels: editorial change, ready to merge

#1086 Editorial: use "is 0" instead of "is zero" for consistency
  spec.html
Labels: editorial change, ready to merge

#2252 Normative: do not apply Early Error for duplicate __proto__ properties when performing JSON.parse
  spec.html
Labels: normative change, ready to merge

#2210 Normative: IntegerIndexedElementSet should always indicate success
  spec.html
Labels: has consensus, has tests, ready to merge

#2248 Editorial: Use Number-literal notation for a few 'length' values
  spec.html
Labels: editorial change, ready to merge

#2255 Markup: Move ul-within-p to outside the p
  spec.html
Labels: editorial change, ready to merge

#2254 Editorial: reword definition of lookahead restrictions
  spec.html
Labels: editorial change, ready to merge

#2250 Normative: Relax the strength of Atomics.compareExchange
  spec.html
Labels: normative change, ready to merge

#2259 Editorial: add missing word
  spec.html
Labels: editorial change, ready to merge
