Repository tc39/ecma262, pull requests merged in 2020-06, with the labels that each got.

#1781 Editorial: A couple fixes from OrdinaryFunctionCreate and undefined arguments
  spec.html
Labels: editorial change, spec bug

#1912 Normative: Promise.{all,allSettled,race} should check resolve is a function before opening their iterable
  spec.html
Labels: has consensus, has tests, normative change

#1996 Editorial: Add <dfn> to well‑known symbols
  spec.html
Labels: editorial change

#2024 Editorial: Add <dfn> for %BigInt.prototype%
  spec.html
Labels: editorial change

#2025 Editorial: Add <dfn>s for TypedArray subclass constructors
  spec.html
Labels: editorial change

#2044 Meta: deploy preview even if lint fails
  .travis.yml
  package.json
Labels: meta

#2049 Editorial: Misc fixes
  spec.html
Labels: editorial change

#2022 Editorial: quick fixes
  spec.html
Labels: editorial change

#2052 Editorial: use step labels rather than numbers to refer to steps
  package-lock.json
  package.json
  spec.html
Labels: editor call, editorial change

#1241 Editorial: Consistency for the term "fully populated Property Descriptor"
  spec.html
Labels: editorial change

#2009 Normative: Add String.prototype.replaceAll
  spec.html
Labels: has stage 4, has tests, normative change, proposal

#2061 Editorial: `BigIntBitwiseOp`: add missing arg types
  spec.html
Labels: editorial change

#1776 Normative: make async iterators next/return/throw not pass `undefined` when value is absent
  spec.html
Labels: has consensus, has tests, normative change

#2067 fixes #2066: add a language tag to the document body
  package-lock.json
  package.json
  spec.html
Labels: meta

#2026 Editorial: Add <dfn>s for native error constructors
  spec.html
Labels: editorial change
