Repository tc39/ecma262, pull requests merged in 2020-01, with the labels that each got.

#1046 Normative: Eliminate extra environment for eval in parameter initializers
  spec.html
Labels: has consensus, has tests, normative change

#1666 Editorial: Remove redundant definitions of ComputedPropertyContains.
  spec.html
Labels: editorial change

#1675 Editorial: Add missing _direction_ parameter in extended regexp pattern evaluate semantics in annex b
  spec.html
Labels: spec bug

#1771 Editorial: Remove extra note from InternalizeJSONProperty
  spec.html
Labels: editorial change

#1791 Normative: specify for-in enumeration order in more cases
  spec.html
Labels: editorial change, has stage 4, has tests, normative change, proposal

#1386 Create LICENSE.md
  LICENSE.md
Labels: meta

#1829 Bugfix: Fix the LexicalEnvironment of the execution context during function parameter eval
  spec.html
Labels: normative change, spec bug

#666 Normative: Add three missing checks in proxy internal methods
  spec.html
Labels: has consensus, has tests, normative change

#1780 Editorial: Tweak casing of "empty String" and "Number value"
  spec.html
Labels: editorial change

#1839 Meta: Stop letting ecmarkup load 262's own outdated bibliography file.
  package.json
Labels: meta, rendering bug

#1826 Normative: Add missing `ReturnIfAbrupt` to “Evaluation of `in` expression”
  spec.html
Labels: normative change, spec bug

#1833 Editorial: Remove erroneous emu-grammar attribute.
  spec.html
Labels: rendering bug

#1847 Editorial: `CreateArrayIterator`: add missing `kind` assertion
  spec.html
Labels: editorial change

#1835 Editorial: Fix outdated Step # references.
  spec.html
Labels: editorial change, spec bug

#1406 Editorial: Fix return value logic for async arrow functions
  spec.html
Labels: spec bug

#1831 Editorial: Clean up some inline notes.
  spec.html
Labels: editorial change

#1842 Editorial: Give emu-notes some color.
  spec.html
Labels: rendering enhancement
