Repository tc39/ecma262, pull requests merged in 2020-07, with the labels that each got.

#2069 Editorial: Relocate the definition of StringIndexOf
  spec.html
Labels: editorial change

#2050 Editorial: add PromiseCapability Record assertions
  spec.html
Labels: editorial change

#2071 Editorial: add oldids for property access section
  spec.html
Labels: editorial change

#2076 Editorial: Add missing part of note in Array `find`/`findIndex`/`forEach`
  spec.html
Labels: editorial change

#1660 Editorial: Remove assertion in InitializeBinding of Object Environment Record
  spec.html
Labels: editorial change

#2059 Editorial: Fix %Generator% and %AsyncGenerator% <dfn>s
  spec.html
Labels: editorial change

#1951 Editorially distinguish host and implementation
  spec.html
Labels: editorial change, has consensus, layering

#2103 Editorial: Don't use "sec-" prefix for dfn ids
  spec.html
Labels: editorial change

#2057 Normative: add `Reflect[Symbol.toStringTag]`
  spec.html
Labels: has consensus, has tests, normative change

#2040 Normative: Add Promise.any & AggregateError
  spec.html
Labels: has stage 4, has tests, normative change, proposal

#2030 Normative: Add Logical Assignment Operators
  spec.html
Labels: has stage 4, has tests, normative change, proposal

#2107 Editorial: Fix <emu‑xref> to AggregateError Objects
  spec.html
Labels: editorial change, spec bug

#2108 Editorial: fix minor errors in step syntax
  spec.html
Labels: editorial change

#1903 Normative: make SharedArrayBuffer optional
  spec.html
Labels: has consensus, normative change

#2054 Normative: Specify \8 and \9 in sloppy non-template strings.
  spec.html
Labels: has consensus, has tests, normative change, web reality

#2094 Normative: Verify if Binding is preserved for obj's SetMutableBinding
  spec.html
Labels: has consensus, needs tests, normative change
