Repository tc39/ecma262, pull requests merged in 2020-05, with the labels that each got.

#1961 Editorial: refactoring the evaluation semantics of compound assignment
  spec.html
Labels: editorial change

#1965 Editorial: quick fixes
  spec.html
Labels: editorial change

#1963 Editorial: Using `is -0` instead of `= -0` in StringGetOwnProperty
  spec.html
Labels: editorial change

#1985 Editorial: end all 'Repeat' steps with commas
  spec.html
Labels: editorial change

#1907 Editorial: Use abstract closures instead of semantic functions
  spec.html
Labels: editorial change

#1977 Editorial: Use DefinePropertyOrThrow and ! prefix in GetTemplateObject
  spec.html
Labels: editorial change

#1974 Editorial: Complete standard preambles for numeric methods
  spec.html
Labels: editorial change

#1936 Editorial: rename LeadSurrgate, TrailSurrogate, and NonSurrogate
  spec.html
Labels: editorial change

#2001 meta: bump ecmarkup
  package-lock.json
  package.json
Labels: meta, rendering bug

#1998 Editorial: make `NumberBitwiseOp`, `BigIntBitwiseOp`, `ByteListBitwiseOp` consistent
  spec.html
Labels: editorial change

#1992 Editorial: use real table rows instead of ULs in Unicode tables
  spec.html
  table-binary-unicode-properties.html
  table-nonbinary-unicode-properties.html
  table-unicode-general-category-values.html
  table-unicode-script-values.html
Labels: editorial change

#1938 Editorial: Early return & throw in Number.prototype.to* methods
  spec.html
Labels: editorial change

#1896 Normative: Update Unicode property lists per Unicode v13
  table-unicode-script-values.html
Labels: has tests, normative change, unicode

#2004 fixes #2002: more precise definition of NumberBitwiseOp and ByteListBitwiseOp
  spec.html
Labels: editorial change

#2005 fixes #2003: consistent wording of "two's complement"
  spec.html
Labels: editorial change

#1939 Normative: Update RegExp property aliases per Unicode v13
  table-binary-unicode-properties.html
Labels: has tests, normative change, unicode

#2006 Editorial: Remove extra "to" in Abstract Operations
  spec.html
Labels: editorial change

#2010 add searchfox link to readme
  README.md
Labels: meta

#1866 Editorial: Extract operation 'ParsePattern'
  spec.html
Labels: editorial change

#1463 Editorial: Fix description of [[ThisMode]] internal slot of Function Object
  spec.html
Labels: editorial change

#2012 Meta: add discourse to readme
  README.md
Labels: meta

#2017 Editorial: fix inconsistent phrase "the empty String value"
  spec.html
Labels: editorial change

#1519 Editorial: Remove unused steps from definitions of Contains
  spec.html
Labels: editorial change

#2020 Editorial: Unify text about refining grammars
  spec.html
Labels: editorial change
