Repository tc39/ecma262, pull requests merged in 2020-03, with the labels that each got.

#1889 Editorial: Introduce abstract closure and use them in RegExps
  spec.html
Labels: editorial change, es2020

#1597 Layering: Allow hosts to cleanly specify Promise Job semantics
  spec.html
Labels: editorial change, es2020, normative change, web reality

#1893 [editorial] Fix typo in NewPromiseReactionJob
  spec.html
Labels: editorial change, spec bug

#1881 Editorial: fix misleading uses of 'operator'
  spec.html
Labels: editorial change

#1899 Editorial: suppress some spurious links to definitions
  package-lock.json
  package.json
  spec.html
Labels: editorial change

#1873 Editorial: correct 'import * circularity' to 'export * circularity'
  spec.html
Labels: editorial change

#1890 Editorial: pass necessary arguments to SerializeJSON*
  spec.html
Labels: editorial change

#1868 Editorial: Annex A tweaks
  spec.html
Labels: editorial change

#1904 Editorial: Quick fixes for recent merges
  spec.html
Labels: editorial change

#1906 Editorial: Spec variables shouldn't use TDZ in their names.
  spec.html
Labels: editorial change

#1911 Meta: replace feature request template with link
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-feature-request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: meta

#1669 Normative: Prevent DFS invariants from being broken
  spec.html
Labels: has consensus, has tests, normative change

#1885 Editorial: Add subscripts to BindingIdentifier static semantics.
  spec.html
Labels: editorial change

#1915 Editorial: added ~async-iterate~ in assertion of ForIn/OfHeadEvaluation
  spec.html
Labels: editorial change, spec bug

#1918 use spec-internal enum in GetOwnPropertyKeys AO
  spec.html
Labels: editorial change

#1921 fix auto-linking of LocalTZA abstract op
  spec.html
Labels: editorial change

#1923 Editorial: Align wording of [[OwnPropertyKeys]] methods
  spec.html
Labels: editorial change

#1922 Editorial: Treat not present flatMap parameter as undefined
  spec.html
Labels: editorial change

#1925 Editorial: Fix TemplateStrings early error for SubstitutionTemplate
  spec.html
Labels: editorial change

#1928 Editorial: List module namespace exports as new in the 11th edition
  spec.html
Labels: editorial change
