Repository tc39/ecma262, pull requests merged in 2020-04, with the labels that each got.

#1892 Normative: add import.meta
  spec.html
Labels: has stage 4, has tests, normative change, proposal

#1869 Normative: Fully specify legal escape sequences in RegExp capture group names
  spec.html
Labels: es2020, has consensus, needs tests, normative change, spec bug

#1932 Normative: allow non-BMP characters in capture group names
  spec.html
Labels: es2020, normative change, spec bug

#1931 Editorial: use correct source text for IsValidRegularExpressionLiteral
  spec.html
Labels: editorial change, spec bug

#1924 Editorial: Tweak Array exotic object internal methods
  spec.html
Labels: editorial change

#1914 Editorial: use consistent wording for abstract operation preambles
  spec.html
Labels: editorial change

#1490 Normative: Set "name" property for anonymous functions
  spec.html
Labels: has consensus, has tests, normative change, web reality

#1860 Editorial: Improve consistency of backtick use for built-ins.
  spec.html
Labels: editorial change

#1943 Editorial: use correct check in B.3.3.6
  spec.html
Labels: editorial change, spec bug

#1949 Editorial: Fix indirect eval environment check
  spec.html
Labels: editorial change, spec bug

#1910 Editorial: Define+use `ClassElementKind`
  spec.html
Labels: editorial change

#1953 Editorial: Convert more abstract operation preambles
  spec.html
Labels: editorial change

#1958 Editorial: reorder step in GetTemplateObject
  spec.html
Labels: editorial change

#1954 Editorial: Fixed typos in variable name `oldvalue`
  spec.html
Labels: editorial change, spec bug

#1946 Editorial: Align wording of The *Function Constructor sections
  spec.html
Labels: editorial change

#1955 Normative: Fixed bug in Number::unsignedRightShift
  spec.html
Labels: es2020, normative change, spec bug

#1956 Normative: Fixed bug in NumberBitwiseOp
  spec.html
Labels: es2020, normative change, spec bug

#1945 Editorial: s/constructable/constructible
  spec.html
Labels: editorial change

#1944 Editorial: Clarify notes on async functions in CreateDynamicFunction
  spec.html
Labels: editorial change

#1933 Editorial: delete some SDO cases that are covered by the chain production rule
  spec.html
Labels: editorial change

#1697 Editorial: Eliminate Lexical Environment
  spec.html
Labels: editorial change

#1976 Editorial: add prefix '?' on calling ToPrimitive in Abstract Equality Comparison
  spec.html
Labels: completion records, editorial change

#1814 Normative: Remove steps 2 and 4 from ProxyCreate
  spec.html
Labels: has consensus, has tests, normative change

#1920 Normative: Generically forbid 402 method extensions in Forbidden Extensions
  spec.html
Labels: has consensus, normative change, spec bug

#1973 Editorial: Reorder a few steps in String.prototype.split
  spec.html
Labels: editorial change

#1326 Editorial: Correct variable terminology
  spec.html
Labels: editorial change

#1979 Editorial: Capitalize Abstract Closure
  spec.html
Labels: editorial change

#1978 Editorial: Fix casing of @@hasInstance well-known symbol
  spec.html
Labels: editorial change

#1969 Editorial: Return an iterator *record* for for...in heads
  spec.html
Labels: editorial change, spec bug

#1408 Normative: Suppress GetMethod errors in IteratorClose
  spec.html
Labels: has consensus, has tests, normative change

#1870 Editorial: Set [[SourceText]] inside OrdinaryFunctionCreate
  spec.html
Labels: editorial change

#1980 [meta] add Begin deploy preview
  .travis.yml
  package-lock.json
  package.json
  scripts/netlify.sh
  scripts/publish-preview.js
Labels: meta
