Repository tc39/ecma262, pull requests merged in 2021-07, with the labels that each got.

#2452 Meta: bump ecmarkup to 8.0.0
  package-lock.json
  package.json
  spec.html
Labels: meta, ready to merge

#2398 Editorial: have CreateIteratorFromClosure provide a new execution context to GeneratorStart
  spec.html
Labels: editorial change, ready to merge, spec bug

#2413 Editorial: Clarify the AsyncGenerator state machine
  spec.html
Labels: editorial change, ready to merge

#2453 Meta: fix auto-deployment
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  scripts/auto-deploy.sh
  scripts/github_deploy_key.enc
Labels: meta, ready to merge

#2382 Editorial: Define+use `list-concatenation`
  spec.html
Labels: editorial change, ready to merge

#2435 Editorial: extract StringNumericValue from MV and add/use RoundStringMVResult helper
  spec.html
Labels: editorial change, ready to merge

#2446 Editorial: Drop grammatical parameters from 'use' productions
  spec.html
Labels: editorial change, ready to merge

#2450 Editorial: Miscellaneous math fixes
  spec.html
Labels: editorial change, ready to merge, spec bug

#2456 Editorial: Fix wrong assertion in IsLessThan
  spec.html
Labels: editorial change, ready to merge, spec bug

#2290 Normative: add `#x in obj` syntax
  spec.html
Labels: has stage 4, has tests, normative change, proposal, ready to merge

#545 Replace each abstract op's preamble with a structured 'header'.
  spec.html
Labels: completion records, editorial change, ready to merge

#2360 Editorial: Remove 'designed to be subclassable'
  spec.html
Labels: editorial change, has consensus, ready to merge

#2448 Normative: Restrict completion values callables can return
  spec.html
Labels: has consensus, normative change, ready to merge

#2367 Editorial: Inline "Dynamic Function SourceText Prefixes" table
  spec.html
Labels: editorial change, ready to merge

#1554 Editorial: Define + use StringToNumber
  spec.html
Labels: editorial change, ready to merge

#2460 Editorial: Validate array length using `SameValueZero` in `ArraySetLength` and `Array`
  spec.html
Labels: ready to merge

#2442 Normative: Constrain all host hooks to return either normal or throw completions
  spec.html
Labels: has consensus, normative change, ready to merge

#2467 Meta: bump ecmarkup to 8.0.1
  package-lock.json
  package.json
Labels: meta, ready to merge

#2125 Normative: move __proto__ out of annex b
  spec.html
Labels: has consensus, has tests, normative change, ready to merge

#2451 Editorial: don't imply that SV, TV, and TRV are shorthands
  spec.html
Labels: editorial change, ready to merge

#2464 Editorial: initialize missing slots in OrdinaryFunctionCreate
  spec.html
Labels: editorial change, ready to merge, spec bug

#2469 Markup: prefer `&notin;` over `&lt;!`
  spec.html
Labels: ready to merge

#2115 Editorial: Define required internal slots in `CreateBuiltinFunction` steps
  spec.html
Labels: editorial change, ready to merge

#2375 Editorial: Split the "TV and TRV" clause into 2 clauses
  spec.html
Labels: editorial change, ready to merge

#2470 Editorial: tweak PropertyDefinitionEvaluation and ClassElementEvaluation
  spec.html
Labels: editorial change, ready to merge
