Repository tc39/ecma262, pull requests merged in 2021-06, with the labels that each got.

#2376 Editorial: Change ValidateTypedArray to not return the buffer
  spec.html
Labels: editorial change, ready to merge

#2424 Editorial: fix typo in Iterator Interface "next" requirements
  spec.html
Labels: editorial change, ready to merge

#2416 Editorial: `meta` should be listed alongside `target`
  spec.html
Labels: editorial change, ready to merge

#2426 Editorial: fix handling of infinities in Math.hypot
  spec.html
Labels: editorial change, ready to merge, spec bug

#2427 Editorial: miscellaneous AO-related cleanups
  spec.html
Labels: editorial change, ready to merge

#2428 Editorial: fix note about var decls in eval in parameter initializers
  spec.html
Labels: ready to merge

#2378 Editorial: Recast comparison algorithms as proper abstract operations
  spec.html
Labels: editorial change, ready to merge

#2431 Meta: CONTRIBUTING.md: Some changes to make the doc more beginner-friendly
  CONTRIBUTING.md
Labels: meta, ready to merge

#2109 Editorial: Add support for Abstract Closures to `CreateBuiltinFunction`
  spec.html
Labels: editorial change, ready to merge

#2439 Editorial: use abstract closures for anonymous functions in more places
  spec.html
Labels: editorial change, ready to merge

#2260 Meta: migrate from travis-ci to Github Actions
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/preview-build.yml
  .github/workflows/preview.yml
  .github/workflows/require-allow-edits.yml
  .travis.yml
  scripts/publish-preview.js
Labels: meta, ready to merge
