Repository tc39/ecma262, pull requests merged in 2021-02, with the labels that each got.

#2284 Editorial: improve “About this Specification” section
  spec.html
Labels: editorial change, ready to merge

#2295 Editorial: swap phrasing to indefinite article for Boolean-coercibles.
  spec.html
Labels: editorial change, ready to merge

#2189 Editorial: convert Number abstract operations to algorithmic steps
  spec.html
Labels: editorial change, ready to merge

#1585 Normative: A more precise Array.prototype.sort
  spec.html
Labels: es2021, has consensus, has tests, normative change, ready to merge

#2221 Normative: Give %TypedArray% methods explicit algorithms.
  spec.html
Labels: es2021, has consensus, has tests, normative change, ready to merge

#2296 Editorial: remove unnecessary assertion
  spec.html
Labels: editorial change, ready to merge

#2297 Editorial: add <dfn> for "TypedArray element type"
  spec.html
Labels: editorial change, ready to merge

#2116 Normative: Set function `name` and `length` in `CreateBuiltinFunction`
  spec.html
Labels: es2021, has consensus, has tests, normative change, ready to merge

#2253 Editorial: Standardize preambles for host-defined abstract operations
  spec.html
Labels: editorial change, ready to merge

#2312 Editorial: Remove paragraph listing similarities to other languages
  spec.html
Labels: editorial change, ready to merge

#2317 Meta: add `scroll-margin-top` CSS to make for a nicer anchor experience
  spec.html
Labels: meta, ready to merge

#2318 Editorial: Fix `<dfn>`s for `WeakRef` and `FinalizationRegistry`
  spec.html
Labels: editorial change, es2021, ready to merge

#2256 Normative: forbid for-of loops with variable named async
  spec.html
Labels: es2021, has consensus, has tests, normative change, ready to merge

#2324 Editorial: swap "about" and "contributing" sections in the intro
  spec.html
Labels: editorial change, ready to merge

#2323 Editorial: nest ASI sections under "ASI" section
  spec.html
Labels: editorial change, ready to merge

#2216 Normative: Define default constructors using spec steps
  spec.html
Labels: es2021, has consensus, has tests, normative change, ready to merge
