Repository tc39/ecma262, pull requests merged in 2021-01, with the labels that each got.

#2257 Editorial: note that JSON is not a semantic subset of ECMAScript
  spec.html
Labels: editorial change, ready to merge

#2268 Editorial: Add ECMA-402 as a Downstream dependency
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: editorial change, meta, ready to merge

#2258 Editorial: reword StringIndexOf in terms of substring
  spec.html
Labels: editorial change, ready to merge

#2045 Editorial: Add Yield, CreateIteratorFromClosure, CreateAsyncIteratorFromClosure abs op.
  spec.html
Labels: editorial change, ready to merge

#1234 Editorial: move Section 25.6 Promise Objects
  spec.html
Labels: editorial change, ready to merge

#2272 Editorial: make EPSILON unambiguously positive
  spec.html
Labels: editorial change, ready to merge

#2273 Editorial: Delete "the Number value for" in Number::leftShift
  spec.html
Labels: editorial change, ready to merge

#2271 Editorial: consolidate each SDO's definition
  spec.html
Labels: editorial change, ready to merge

#2213 Editorial: List the [[Construct]]-requires-[[Call]] invariant in the list of invariants
  spec.html
Labels: editorial change, ready to merge

#2282 Editorial: add missing assertion to ApplyStringOrNumericBinaryOperator
  spec.html
Labels: editorial change, ready to merge

#2280 Editorial: split up IterationStatement
  spec.html
Labels: ready to merge

#2289 Meta: bump ecmarkup to 6.0.0
  package-lock.json
  package.json
  spec.html
Labels: meta, ready to merge

#2275 Editorial: Merge the RHSs of AsyncFunctionExpression
  spec.html
Labels: editorial change, ready to merge
