Repository tc39/ecma262, pull requests merged in 2021-11, with the labels that each got.

#2356 Normative: add error cause
  spec.html
Labels: normative change, has tests, proposal, has stage 4, ready to merge

#2566 Editorial: mostly stop using strings for special values
  spec.html
Labels: editorial change, ready to merge

#2561 Editorial: `find`/`findIndex`: update note about delete before visit
  spec.html
Labels: editorial change, ready to merge

#2573 Editorial: Disambiguate "This property"
  spec.html
Labels: editorial change, ready to merge

#2154 Normative: Arbitrary module namespace identifier names
  spec.html
Labels: normative change, has consensus, has tests, ready to merge

#2559 Editorial: Remove <SP> and <NBSP> as the ones already included by <USP>
  spec.html
Labels: editorial change, ready to merge

#2577 Editorial: fix a couple typos
  spec.html
Labels: editorial change, ready to merge

#2571 Editorial: Increase precision for referencing source text of a Parse Node
  spec.html
Labels: editorial change, ready to merge

#2572 Editorial: Be consistent about the sense of "match" (and other phrasing)
  spec.html
Labels: editorial change, ready to merge

#2574 Editorial: replace most occurrences of "has the value" with "is"
  spec.html
Labels: editorial change, ready to merge

#2575 Editorial: Consistify prose for same-value properties
  spec.html
Labels: editorial change, ready to merge

#2583 Meta: bump ecmarkup to 9.6.3
  package-lock.json
  package.json
Labels: ready to merge
