Repository tc39/ecma262, pull requests merged in 2021-05, with the labels that each got.

#1655 (ignore) Normative: Add public and private class fields
  spec.html
Labels: has tests, normative change, pending stage 4, proposal

#1667 (ignore) Normative: Add private methods and getter/setters.
  spec.html
Labels: has tests, normative change, pending stage 4, proposal

#1668 Normative: Add public and private class fields, static class features, private methods & getters/setters
  spec.html
Labels: has stage 4, has tests, normative change, proposal, ready to merge

#2393 Normative: Make SharedArrayBuffer's sole parameter required
  spec.html
Labels: has consensus, has tests, normative change, ready to merge, web reality
