Repository tc39/ecma262, pull requests merged in 2021-03, with the labels that each got.

#2331 Editorial: Fix mistakes
  spec.html
Labels: editorial change, ready to merge

#2330 Editorial: Consistify some "For each" steps
  spec.html
Labels: editorial change, ready to merge

#2333 Editorial: Align checks order in [[DefineOwnProperty]] overrides with ordinary method
  spec.html
Labels: editorial change, ready to merge

#2340 Meta: better compression during preview uploads
  package-lock.json
  package.json
  scripts/publish-preview.js
Labels: meta, ready to merge

#2342 Editorial: Clarify ES2021 Array.prototype.sort change
  spec.html
Labels: editorial change

#2329 Normative: specify creation order for capturing group properties
  spec.html
Labels: has consensus, has tests, normative change, ready to merge, web reality

#2316 Normative: Use HostJobCallbacks for FinalizationRegistry callbacks
  spec.html
Labels: has consensus, normative change, ready to merge, web reality

#2287 Editorial: Object Environment Record improvements
  spec.html
Labels: editorial change, ready to merge

#2341 Editorial: use target alias name instead of "it"
  spec.html
Labels: editorial change, ready to merge

#2346 Editorial: clean up wording of Array methods
  spec.html
Labels: editorial change, ready to merge

#2351 Editorial: small tweaks
  spec.html
Labels: editorial change, ready to merge

#2359 Editorial: Fix early error rules of 'IfStatement'
  spec.html
Labels: editorial change, ready to merge

#2350 Editorial: Eliminate `CoveredFoo` SDOs
  spec.html
Labels: editorial change, ready to merge

#2363 Editorial: Consistent notation of newly created error object
  spec.html
Labels: editorial change, ready to merge
