Repository tc39/ecma262, pull requests merged in 2021-09, with the labels that each got.

#2415 Normative: Add `Object.hasOwn`
  spec.html
Labels: normative change, has tests, proposal, has stage 4, ready to merge

#2440 Normative: Add class `static` initialization blocks
  spec.html
Labels: normative change, has tests, proposal, has stage 4, ready to merge

#2495 Normative: phrase tail calls as discarding resources rather than popping execution context stack
  spec.html
Labels: normative change, has consensus, has tests, ready to merge

#2475 Editorial: Update restricted productions summary
  spec.html
Labels: ready to merge

#2493 Normative: Add relative indexing method at()
  spec.html
Labels: normative change, has tests, proposal, has stage 4, ready to merge

#2404 Editorial: add missing constructor property of the global object
  spec.html
Labels: editorial change, spec bug, ready to merge

#2482 Normative: `continue` labels should not pass through blocks
  spec.html
Labels: normative change, web reality, has consensus, has tests, ready to merge

#2499 Editorial: fix slight ambiguity in ToPrimitive note about Dates
  spec.html
Labels: editorial change, ready to merge

#2500 Editorial: tweak note in FunctionDeclarationInstantiation
  spec.html
Labels: ready to merge

#2504 Editorial: make the order of parameters for class field AOs more consistent
  spec.html
Labels: editorial change, ready to merge

#2509 Editorial: fix typos in Math.cos and Math.cosh
  spec.html
Labels: editorial change, spec bug, ready to merge

#2510 Editorial: Make the behavior of SameValue and SameValueZero a little more clear
  spec.html
Labels: editorial change, ready to merge

#2513 Editorial: Quick fixes
  spec.html
Labels: editorial change, ready to merge

#2406 Editorial: Fix some SDOs
  spec.html
Labels: editorial change, ready to merge

#2441 Editorial: disambiguate `with` statement's status
  spec.html
Labels: editorial change, has consensus, ready to merge

#2505 Normative: add missing AsyncGenerator cases to ContainsArguments
  spec.html
Labels: normative change, spec bug, ready to merge

#2520 CONTRIBUTING.md: Update IRC to Matrix
  CONTRIBUTING.md
Labels: meta, ready to merge

#2521 Meta: update static default branch name to a dynamic one
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/deploy.yml
  FAQ.md
  LICENSE.md
  README.md
  scripts/check-commit.js
  scripts/check-form.js
  spec.html
  stage0.md
  withdrawn-proposals.md
Labels: meta, ready to merge

#2524 Editorial: Provide `<emu-alg>` for 6 BigInt methods
  spec.html
Labels: editorial change, ready to merge

#2512 Markup: have SDOs use structured headers
  package-lock.json
  package.json
  spec.html
Labels: ready to merge

#2527 Editorial: "ECMAScript value" -> "ECMAScript language value"
  spec.html
Labels: editorial change, ready to merge

#2490 Editorial: Use consistent language to reference intrinsic constructors
  spec.html
Labels: ready to merge

#2517 Meta: twelfth -> thirteenth
  spec.html
Labels: meta, ready to merge

#2519 Editorial: remove gratuitous detail in note about UTF-8 encoding
  spec.html
Labels: editorial change, ready to merge

#2501 Clarify ToIndex, ToLength, and ToIntegerOrInfinity
  spec.html
Labels: ready to merge

#2335 Editorial: Define Module Namespace's [[GetPrototypeOf]] method
  spec.html
Labels: editorial change, ready to merge

#2532 Meta: Keep old years in gh-pages
  .github/workflows/deploy.yml
  scripts/auto-deploy.sh
Labels: meta, ready to merge

#2392 Editorial: Improve specification of [RegExp]IdentifierNames
  spec.html
Labels: editorial change, ready to merge

#2536 Editorial: `String.prototype.lastIndexOf`: use explicit algorithm steps
  spec.html
Labels: editorial change, ready to merge

#2537 Editorial: `lastIndexOf`: fix typo from #2536
  spec.html
Labels: editorial change, spec bug, ready to merge

#2457 Editorial: Document parameter type for Date Abstract Operations
  spec.html
Labels: editorial change, ready to merge
