Repository tc39/ecma262, pull requests merged in 2022-04, with the labels that each got.

#2718 Meta: bump ecmarkup to 12.0.1
  package-lock.json
  package.json
  scripts/publish-biblio.sh
  spec.html
Labels: meta, ready to merge

#2723 Normative: Remove detach check in TypedArray.prototype.sort comparator
  spec.html
Labels: normative change, has consensus, has tests, ready to merge

#2713 Editorial: remove namespace from algorithm conventions clause
  spec.html
Labels: editorial change, ready to merge

#2720 Editorial: mark user code in SortIndexedProperties
  spec.html
Labels: editorial change, ready to merge

#2728 Editorial: Fix "classFieldIntializerName" spelling error in PerformEval
  spec.html
Labels: editorial change, ready to merge

#2704 Editorial: Fix CreateUnmappedArgumentsObject's return-type
  spec.html
Labels: editorial change, spec bug, ready to merge

#2646 Normative: Use IntegerIndexedElementSet in %TypedArray%.prototype.set
  spec.html
Labels: normative change, has consensus, has tests, ready to merge

#2731 Refactor the "enforce format" job to output literal backticks rather than command output
  .github/workflows/enforce-format.yml
Labels: meta, ready to merge

#2719 Normative: remove Symbol.species from InitializeTypedArrayFromTypedArray
  spec.html
Labels: normative change, has consensus, has tests, ready to merge

#2732 Editorial: `splice`: consolidate redundant count variables
  spec.html
Labels: editorial change, ready to merge

#2733 Editorial: note about arguments immutability in strict code
  spec.html
Labels: editorial change, ready to merge

#2736 Editorial: Use "surrounding agent" in favor of "calling agent"
  spec.html
Labels: editorial change, ready to merge

#2738 Editorial: Use proper Unicode vocabulary
  spec.html
Labels: editorial change, ready to merge

#2735 Editorial: clarify that built-in functions may lack [[Construct]]
  spec.html
Labels: editorial change, ready to merge

#2712 Editorial: Align the algorithm steps and description of CanonicalNumericIndexString
  spec.html
Labels: ready to merge

#2748 Editorial: Remove unused variable from String.fromCharCode()
  spec.html
Labels: editorial change, ready to merge

#2625 Editorial: Eliminate `_NcapturingParens_` from Early Error rules + grammar
  spec.html
Labels: editorial change, spec bug, ready to merge

#2727 Editorial: Note that StringNumericLiteral cannot contain NumericLiteralSeparator
  spec.html
Labels: editorial change, ready to merge

#2729 Normative: allow named capture groups in Annex B non-u regex grammar
  spec.html
Labels: normative change, spec bug, ready to merge

#2676 Editorial: Change many "abrupt completion" to "throw completion"
  spec.html
Labels: editorial change, ready to merge

#2670 Normative: Remove callerRealm from HostEnsureCanCompileStrings
  spec.html
Labels: normative change, has consensus, ready to merge

#2705 Editorial: Improve consistency of property and record field names
  spec.html
Labels: ready to merge

#2750 Editorial: Consistently use U+002D `-` rather than U+2212 `−` for subtraction
  spec.html
Labels: ready to merge

#2746 Editorial: Use consistent phrasing for string length
  spec.html
Labels: editorial change, ready to merge, consistent phrasing

#2754 Meta: bump ecmarkup to 12.0.3
  package-lock.json
  package.json
Labels: meta, ready to merge

#2610 Editorial: GlobalDeclarationInstantiation takes a Script
  spec.html
Labels: editorial change, spec bug, ready to merge

#2622 Editorial: Use consistent phrasing for parameters that are Number or BigInt
  spec.html
Labels: editorial change, ready to merge, consistent phrasing

#2722 Editorial: Fix wording bug by tweaking CapturingGroupName
  spec.html
Labels: editorial change, spec bug, ready to merge

#2741 Editorial: Declare "JSON Serialization Record"
  spec.html
Labels: editorial change, ready to merge
