Repository tc39/ecma262, pull requests merged in 2022-03, with the labels that each got.

#2666 Editorial: "a new empty List" -> "&laquo; &raquo;"
  spec.html
Labels: editorial change, ready to merge, consistent phrasing

#2675 Meta: publish biblio to npm
  .github/workflows/publish-biblio.yml
  biblio/README.md
  biblio/package.json
  scripts/publish-biblio.sh
Labels: meta, ready to merge

#2679 Meta: fix biblio publish job
  .github/workflows/publish-biblio.yml
Labels: meta, ready to merge

#2680 Meta: fix biblio publish job, take 2
  .github/workflows/publish-biblio.yml
Labels: meta, ready to merge

#2682 Editorial: Eliminate 'bare' uses of "completion"
  spec.html
Labels: editorial change, ready to merge

#2377 Editorial: Simplify getting the Element Type/Size for a TypedArray
  spec.html
Labels: editorial change, ready to merge

#2305 Editorial: Factor out common `sort` functionality
  spec.html
Labels: ready to merge

#2689 Meta: biblio: add `commit` field to package.json every publish
  biblio/package.json
  scripts/publish-biblio.sh
Labels: meta, ready to merge

#2690 Meta: remove mistaken "infallibly" IDs from #2547
  spec.html
Labels: meta, ready to merge

#1713 Normative: add RegExp Match Indices
  spec.html
Labels: normative change, has tests, proposal, has stage 4, ready to merge, es2022

#2696 Editorial: fix type confusion in msFromTime
  spec.html
Labels: editorial change, spec bug, ready to merge, es2022

#2687 Editorial: fix ambiguity in Annex B definition of typeof semantics
  spec.html
Labels: editorial change, ready to merge

#2688 Editorial: work around ecmarkup limititation with replacement step numbering
  spec.html
Labels: editorial change, ready to merge

#2686 Editorial: eliminate unnecessary phrasing that explains how return works
  spec.html
Labels: editorial change, ready to merge

#2684 Editorial: tweak DestructuringAssignmentEvaluation
  spec.html
Labels: editorial change, ready to merge

#2691 Editorial: Expand the use of 'type' syntax
  spec.html
Labels: editorial change, ready to merge, consistent phrasing

#2710 Editorial: Fix typo
  spec.html
Labels: ready to merge

#2699 Editorial: Add ToZeroPaddedDecimalString abstract operation.
  spec.html
Labels: editorial change, ready to merge

#2700 Editorial: Handled -0 case in 'Number::multiply'
  spec.html
Labels: normative change, spec bug, editor call, ready to merge, es2022

#2714 Editorial: MakeMatchIndicesIndexPairArray: avoid creating a property on undefined
  spec.html
Labels: editorial change, spec bug, ready to merge, es2022

#2715 Editorial: `ToZeroPaddedDecimalString`: this AO is nonsensical on a negative integer
  spec.html
Labels: editorial change, ready to merge, es2022

#2698 Editorial: Fix the return-type of CompilePattern
  spec.html
Labels: editorial change, spec bug, ready to merge, es2022

#2707 Editorial: Improve text for "locale-sensitive" operations
  spec.html
Labels: ready to merge

#2709 Editorial: Add ES2022 features
  spec.html
Labels: editorial change, es2022
