Repository tc39/ecma262, pull requests merged in 2022-09, with the labels that each got.

#2649 Normative: remove tables of Unicode property values and aliases
  spec.html
  table-unicode-general-category-values.html
  table-unicode-script-values.html
Labels: normative change, has consensus, ready to merge

#2788 Editorial: Fix remaining phrases using 'the number of code units in' for string length
  spec.html
Labels: editorial change, ready to merge, consistent phrasing

#2821 Editorial: clarify spec values that have identity and its implications
  spec.html
Labels: editorial change, ready to merge, consistent phrasing

#2866 Editorial: clarify BigInt.prototype.toString for non-decimal radices
  spec.html
Labels: editorial change, ready to merge

#2867 Editorial: get rid of BigInt::sameValue and BigInt::sameValueZero
  spec.html
Labels: editorial change, ready to merge

#2874 Editorial: avoid using Type macro for simple type tests
  spec.html
Labels: editorial change, ready to merge, consistent phrasing

#2878 Editorial: refactor String.fromCharCode to build a String directly
  spec.html
Labels: editorial change, ready to merge

#2882 Editorial: turn "no action is required" step in Array reverse into note
  spec.html
Labels: editorial change, ready to merge

#2879 Editorial: remove some unnecessary complexity due to the SourceText AO
  spec.html
Labels: editorial change, ready to merge

#2884 Editorial: Add note that roundtripping ToIntegerOrInfinity never produces -0
  spec.html
Labels: ready to merge

#2885 Editorial: quick fixes for PR #2874
  spec.html
Labels: editorial change, ready to merge

#2890 Editorial: Expand on "a List"
  spec.html
Labels: editorial change, ready to merge

#2892 Editorial: Change CreateDataPropertyOrThrow's normal return
  spec.html
Labels: editorial change, ready to merge

#2900 Editorial: split variable declarations into their own lines in JSON.stringify
  spec.html
Labels: editorial change, ready to merge

#2899 Editorial: rename EnumerableOwnPropertyNames to EnumerableOwnProperties
  spec.html
Labels: editorial change, ready to merge

#2839 Editorial: Consolidate use of ASCII subsets
  spec.html
Labels: ready to merge

#2908 Editorial: use consistent wording in [[NoTear]] explanation for read/write events
  spec.html
Labels: editorial change, ready to merge, consistent phrasing

#2910 Editorial: replace any occurrences of "nonempty" with "non-empty"
  spec.html
Labels: editorial change, ready to merge, consistent phrasing

#2844 Editorial: Revert unintentional normative change for String.prototype.substr
  spec.html
Labels: normative change, spec bug, ready to merge

#2861 Editorial: Fix completion in CreateListIteratorRecord and CreateArrayIterator
  spec.html
Labels: editorial change, ready to merge

#2894 Editorial: Tweak ScriptEvaluation
  spec.html
Labels: editorial change, ready to merge

#2906 Editorial: tweak a code sample
  spec.html
Labels: editorial change, ready to merge

#1418 Editorial: Explain why *_SAFE_INTEGER magnitude is not a power of two
  spec.html
Labels: editorial change, ready to merge

#2745 Editorial: Eliminate "unknown" as a parameter type
  spec.html
Labels: editorial change, ready to merge

#2859 Editorial: add stars around null values that are missing them
  spec.html
Labels: editorial change, ready to merge

#2875 Editorial: use "is not finite" in more places where appropriate and add dfn for "finite" so they link
  spec.html
Labels: editorial change, ready to merge

#2887 Editorial: Eliminate mutable String values
  spec.html
Labels: editorial change, ready to merge

#2912 Editorial: Add 'AsciiLetter' to Annex A
  spec.html
Labels: editorial change, ready to merge

#2850 Editorial: Relocate some RegExp-related operations
  spec.html
Labels: editorial change, ready to merge

#2916 Editorial: Define alias before reference
  spec.html
Labels: editorial change, ready to merge

#2751 Editorial: Replace mixtures of spec aliases with language operators
  spec.html
Labels: editorial change, ready to merge

#2783 Editorial: Refactor String.raw in anticipation of generalization
  spec.html
Labels: editorial change, ready to merge

#2876 Editorial: define `\d` semantics in a similar way to `\s`, avoiding character range
  spec.html
Labels: editorial change, ready to merge

#2880 Editorial: dfn the Pattern data structures
  spec.html
Labels: editorial change, ready to merge

#2883 Editorial: in NumericToRawBytes, consolidate byte ordering decision
  spec.html
Labels: editorial change, ready to merge

#2888 Editorial: Subdivide the "Grammar Notation" section
  spec.html
Labels: editorial change, ready to merge

#2891 Editorial: Have NewGlobalEnvironment invoke NewDeclarativeEnvironment
  spec.html
Labels: editorial change, ready to merge

#2893 Editorial: Refactor TemplateStrings SDO
  spec.html
Labels: editorial change, ready to merge

#2911 Editorial: refactor remainder AOs
  spec.html
Labels: editorial change, ready to merge

#2711 Editorial: Improve consistency of referring to String values
  spec.html
Labels: ready to merge, consistent phrasing
