Repository tc39/ecma262, pull requests merged in 2022-07, with the labels that each got.

#2827 Editorial: `OrdinaryCreateFromConstructor`: correctly handle an omitted internalSlotsList
  spec.html
Labels: editorial change, ready to merge

#2476 Normative: Add array-find-from-last
  spec.html
Labels: normative change, has tests, proposal, has stage 4, ready to merge

#2830 Meta: Specification text uses alternate policy
  LICENSE.md
Labels: meta, ready to merge

#2836 Editorial: remove unused capture in %TypedArray%.prototype.sort
  spec.html
Labels: ready to merge

#2768 Editorial: Declare iteration aliases as close to iterations as practical
  spec.html
Labels: editorial change, ready to merge

#2834 Editorial: Fix typo in CharacterValue
  spec.html
Labels: ready to merge

#2837 Editorial: add missing `<dfn>`s for different kinds of code
  spec.html
Labels: editorial change, ready to merge
