Repository tc39/ecma262, pull requests merged in 2022-01, with the labels that each got.

#2302 Editorial: Give TypedArraySortCompare its own sub-clause
  spec.html
Labels: editorial change, ready to merge

#2602 Editorial: Reword field 'types'
  spec.html
Labels: editorial change, ready to merge

#2605 Editorial: Eliminate "the code point value of X"
  spec.html
Labels: editorial change, ready to merge

#2614 Meta: delete "workingdocs"
  workingdocs/ES6-super-construct=proposal.md
  workingdocs/callconstructor.md
Labels: meta, ready to merge

#2468 Editorial: Cleanup ValidateAndApplyPropertyDescriptor and own prop operations
  spec.html
Labels: editorial change, ready to merge

#2621 Editorial: Quick fixes re PR #2468
  spec.html
Labels: editorial change, ready to merge

#2620 Editorial: consistently test whether a field is present
  spec.html
Labels: editorial change, ready to merge

#2391 Editorial: Simplify RegExpInitialize
  spec.html
Labels: editorial change, ready to merge

#2604 Editorial: Introduce the term "must cover" (replaces "is [not] covering")
  spec.html
Labels: editorial change, ready to merge

#2619 Markup: add `sdo` types to `emu-clause` in missing parts
  spec.html
Labels: ready to merge, markup

#2594 Editorial: Use `<code>` for values from other specifications
  spec.html
Labels: editorial change, ready to merge

#2353 Editorial: Rename some aliases
  spec.html
Labels: editorial change, ready to merge

#2552 Editorial: Fix parameter type in InnerModuleLinking
  spec.html
Labels: editorial change, ready to merge

#2603 Editorial: Note how edge case in GetSubstitution can arise
  spec.html
Labels: editorial change, ready to merge

#2609 Editorial: Improve function creation text
  spec.html
Labels: editorial change, ready to merge

#2617 Editorial: Fix sign of zero in Number::remainder
  spec.html
Labels: editorial change, spec bug, ready to merge

#2626 Editorial: Use consistent wording for SDO application with argument(s)
  spec.html
Labels: editorial change, ready to merge

#2629 Meta: bump ecmarkup to 9.8.0
  package-lock.json
  package.json
Labels: ready to merge

#2627 Markup: add missing `example` attributes to example algorithms
  spec.html
Labels: ready to merge, markup
