Repository tc39/ecma262, pull requests merged in 2022-05, with the labels that each got.

#2760 Meta: Update URLs to WebIDL spec/issue tracker in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: meta, ready to merge

#2767 Editorial: Fix incorrect SetMutableBinding infallibility assumption
  spec.html
Labels: editorial change, spec bug, ready to merge

#2776 Editorial: Remove use of "must" from liveness note
  spec.html
Labels: editorial change, ready to merge

#2764 Editorial: Mark concrete method calls of Environment Records with ?/!
  spec.html
Labels: editorial change, completion records, ready to merge

#2755 Editorial: Add missing preposition
  spec.html
Labels: ready to merge

#2757 Editorial: Properly handle comparison results as Number values
  spec.html
Labels: editorial change, ready to merge

#2739 Editorial: Simplify GetSubstitution
  spec.html
Labels: ready to merge

#2779 Normative: Add missing `d` flag character to IsValidRegularExpressionLiteral
  spec.html
Labels: normative change, spec bug, ready to merge

#2737 Editorial: Make the steps of IsLessThan for String values more explicit
  spec.html
Labels: ready to merge
