Repository tc39/ecma262, pull requests merged in 2022-08, with the labels that each got.

#2592 Editorial: Consistify prose for intrinsic functions
  spec.html
Labels: editorial change, ready to merge, consistent phrasing

#2744 Editorial: Make `Evaluation` more like regular SDOs
  spec.html
Labels: editorial change, spec bug, ready to merge, consistent phrasing

#2806 Editorial: Clarify that the `HostResolveImportedModule` cache is per-Realm
  spec.html
Labels: editorial change, ready to merge

#2822 Editorial: change dfn for "mathematical value" and add "mathematical value of"
  spec.html
Labels: editorial change, ready to merge

#2550 Normative: Clarify validity of negative expanded year 0.
  spec.html
Labels: normative change, web reality, has consensus, ready to merge

#2791 Normative: Always check regular expression flags by "flags"
  spec.html
Labels: normative change, has consensus, has tests, ready to merge

#2812 Normative: only coerce once in BigInt constructor
  spec.html
Labels: normative change, web reality, has consensus, has tests, ready to merge

#2843 Editorial: move RegExpHasFlag out of the dotAll section
  spec.html
Labels: editorial change, ready to merge

#2790 Editorial: Consistify miscellaneous phrases
  spec.html
Labels: editorial change, ready to merge, consistent phrasing

#2852 Editorial: Use StringPad rather than "padded" prose
  spec.html
Labels: editorial change, ready to merge

#2640 Editorial: Capitalize Environment Record subtype names
  spec.html
Labels: editorial change, ready to merge

#2801 Editorial: `HostImportModuleDynamically`'s specifier can be any string
  spec.html
Labels: ready to merge

#1556 Normative: Guard IntegerIndexedElementSet with receiver check
  spec.html
Labels: normative change, spec bug, needs tests, web reality, has consensus, ready to merge

#2759 Editorial: Correct notes in Create{Method,NonEnumerableData}Property
  spec.html
Labels: editorial change, ready to merge

#2766 Editorial: Specify Map/Set forEach more explicitly
  spec.html
Labels: ready to merge

#2773 Editorial: Improve the numeric string grammar summary
  spec.html
Labels: ready to merge

#2787 Editorial: Differentiate code point identity (U+…) from value (MV, usually hex)
  spec.html
Labels: ready to merge

#2820 Editorial: replace ECMAScript "code" with "source text" as appropriate
  spec.html
Labels: editorial change, ready to merge

#2807 Normative: allow host exotic objects to reject private fields
  spec.html
Labels: normative change, has consensus, ready to merge

#2853 Editorial: properly define and `<dfn>` spec enums
  spec.html
Labels: editorial change, ready to merge

#2816 Normative: add hashbang comments
  spec.html
Labels: normative change, has consensus, has tests, proposal, has stage 4, ready to merge

#2855 Editorial: fix typo in Set.prototype.forEach
  spec.html
Labels: editorial change, ready to merge

#2857 Editorial: remove misleading sentence about outdated use of "empty"
  spec.html
Labels: editorial change, ready to merge

#2858 Editorial: Fixups for hashbang PR
  spec.html
Labels: editorial change, ready to merge

#2851 Editorial: refactor ForIn/OfBodyEvaluation
  spec.html
Labels: editorial change, ready to merge

#2854 Editorial: clarify string representation of numbers with radix ≠ 10
  spec.html
Labels: editorial change, ready to merge

#2842 Editorial: GetValue and PutValue do not need to unwrap Completion Records
  spec.html
Labels: editorial change, ready to merge

#2862 Editorial: replace implicit `~[empty]~` in ForBodyEvaluation with explicit `~empty~`
  spec.html
Labels: editorial change, ready to merge

#2817 Editorial: IfAbrupt macros only take completion records
  spec.html
Labels: ready to merge

#2864 Meta: bump ecmarkup to 14.1.1
  package-lock.json
  package.json
Labels: ready to merge

#2872 Meta: properly fix IPR script (#2872)
  scripts/check-form.js
Labels: meta

#2863 Editorial: bugfix for exponentiation of Number and BigInt
  spec.html
Labels: editorial change, spec bug, ready to merge

#1838 Editorial: Improve `Array.[[DefineOwnProperty]]` length variable names
  spec.html
Labels: editorial change, ready to merge

#2747 Editorial: Make the steps of GetStringIndex more explicit
  spec.html
Labels: ready to merge
