Repository tc39/ecma262, pull requests merged in 2022-02, with the labels that each got.

#2647 Editorial: Suppress user-code on CloneArrayBuffer in TA.p.set
  spec.html
Labels: ready to merge

#2648 Editorial: NormalCompletion/ThrowCompletion create a Completion Record
  spec.html
Labels: editorial change, completion records, ready to merge

#2136 Normative: Fix out-of-range NaNs in date set methods
  spec.html
Labels: normative change, spec bug, has consensus, has tests, ready to merge, es2022

#2591 Editorial: Add `Iterator Record` type
  spec.html
Labels: editorial change, editor call, ready to merge

#2624 Editorial: Eliminate "present" and "absent" fields
  spec.html
Labels: editorial change, ready to merge, consistent phrasing

#2667 Editorial: disambiguate NotifyWaiter calls
  spec.html
Labels: editorial change, ready to merge

#2547 Editorial: remove implicit wrapping/unwrapping of completion records
  package-lock.json
  package.json
  spec.html
Labels: editorial change, ready to merge
