Repository tc39/ecma262, pull requests merged in 2023-03, with the labels that each got.

#2997 Normative: Adds change-array-by-copy
  spec.html
Labels: normative change, has test262 tests, proposal, has stage 4, editor call, ready to merge

#3026 Editorial: mark a note step as a note
  spec.html
Labels: editorial change, ready to merge

#3025 Editorial: fix the Unary - Operator's description
  spec.html
Labels: editorial change, ready to merge

#3027 Editorial: Clarify identity as from perspective of spec vs language
  spec.html
Labels: editorial change, editor call, ready to merge

#2777 Normative: Permit Symbols as WeakMap keys
  spec.html
Labels: normative change, has test262 tests, proposal, has stage 4, ready to merge

#2974 Editorial: Increase consistency and clarity of string operations
  spec.html
Labels: editorial change, ready to merge, establishes editorial conventions

#3031 Editorial: Quick follow-ups to recent merges
  spec.html
Labels: editorial change, ready to merge

#3021 Editorial: Clarify GetIterator
  spec.html
Labels: editorial change, ready to merge

#3032 Editorial: describe changes in es2023 and sign introduction
  spec.html
Labels: ready to merge
