Repository tc39/ecma262, pull requests merged in 2023-04, with the labels that each got.

#3034 replace an unnecessary GetV with a Get
  spec.html
Labels: editorial change, ready to merge

#3018 Meta: bump ecmarkup to 16.1.1
  package-lock.json
  package.json
Labels: meta, ready to merge

#3038 Editorial: Fix notes about explicit setting of "length" in certain Array methods
  spec.html
Labels: ready to merge

#3041 Meta: bump ecmarkup to 16.2.0
  package-lock.json
  package.json
Labels: ready to merge

#2995 Editorial: consistent "*undefined* or *null*" ordering
  spec.html
Labels: editorial change, ready to merge

#3029 Editorial: Remove incorrect equivalence claim for RegExp constructor
  spec.html
Labels: editorial change, ready to merge

#3040 Editorial: reduce filler words in Math.fround
  spec.html
Labels: editorial change, ready to merge

#3043 Editorial: Avoid preceding a multi-step Else with a collapsed single-step If
  spec.html
Labels: editorial change, establishes editorial conventions
