Repository tc39/ecma262, pull requests merged in 2023-09, with the labels that each got.

#3173 Editorial: remove unused isLittleEndian parameter of GetModifySetValueInBuffer
  spec.html
Labels: editorial change, ready to merge

#3162 Editorial: use proper comparison operation in LabelledEvaluation of LabelledStatement
  spec.html
Labels: editorial change, ready to merge

#3178 Meta: bump ecmarkup to v18.0.0
  package-lock.json
  package.json
Labels: meta, ready to merge

#3145 Editorial: Stop saying that a built-in function can be implemented as an ECMAScript function
  spec.html
Labels: editorial change, ready to merge

#3182 Markup: dfn "integer-indexed"
  spec.html
Labels: ready to merge, markup
