Repository tc39/ecma262, pull requests merged in 2023-10, with the labels that each got.

#3192 Remove redundant parenthesis
  CONTRIBUTING.md
Labels: meta, ready to merge

#3116 Normative: Add resizable ArrayBuffer and growable SharedArrayBuffer
  esmeta-ignore.json
  spec.html
Labels: normative change, has test262 tests, proposal, has stage 4, ready to merge

#3157 Normative: Update GetSubstitution to match reality
  spec.html
Labels: normative change, web reality, has consensus, has test262 tests, ready to merge

#3146 Editorial: move built-in constructor into its own Terms & Definitions section
  spec.html
Labels: editorial change, ready to merge

#3187 Editorial: dfn PromiseReaction Records
  spec.html
Labels: editorial change, ready to merge

#3196 Markup: Eliminate unnecessary <emu-xref> elements
  spec.html
Labels: ready to merge, markup, establishes editorial conventions

#3197 Editorial: Model CaptureRange and MatchState as Records
  spec.html
Labels: editorial change, ready to merge

#3200 Normative bug fix: Fix RevalidateAtomicAccess to check against byte length
  spec.html
Labels: spec bug, ready to merge

#3202 Editorial: remove some unnecessary calls to SameValue
  spec.html
Labels: editorial change, ready to merge

#3205 Editorial: Rename indexedPosition to byteIndexInBuffer
  spec.html
Labels: editorial change, ready to merge

#3148 Editorial: widen parameter type of IsAnonymousFunctionDefinition
  spec.html
Labels: editorial change, ready to merge

#3152 Markup: add alt text to Ecma logo
  spec.html
Labels: ready to merge, markup

#3169 Editorial: fix invalid assertion in Number::lessThan
  spec.html
Labels: editorial change, spec bug, ready to merge
