Repository tc39/ecma262, pull requests merged in 2023-01, with the labels that each got.

#2960 Editorial: Make more use of sign-preserving truncate
  spec.html
Labels: editorial change, ready to merge

#2955 Editorial: Clarify proxy operations with a named helper operation
  spec.html
Labels: ready to merge

#2973 Normative: Allow implementations to pad timeouts in SuspendAgent
  spec.html
Labels: normative change, has consensus, ready to merge

#2681 Editorial: Use Abstract Closure to set the code eval state
  spec.html
Labels: editorial change, ready to merge

#2941 Editorial: Consistify re "elements in/of"
  spec.html
Labels: editorial change, ready to merge, establishes editorial conventions

#2963 Editorial: Correct the 'Value Type' of a few Record fields
  spec.html
Labels: editorial change, ready to merge

#2964 Editorial: Rephrase 2 "List of Records" types
  spec.html
Labels: editorial change, ready to merge, establishes editorial conventions

#2980 Editorial: Create PromiseCapability Record with non-transient field values
  spec.html
Labels: editorial change, ready to merge

#2998 Editorial: Indicate the lack of user effects in ToNumber(_primValue_)
  spec.html
Labels: editorial change, ready to merge

#2999 Editorial: Use the preferred indication for example grammars
  spec.html
Labels: ready to merge

#2877 various editorial changes for comparisons
  esmeta-ignore.json
  spec.html
Labels: editorial change, ready to merge, establishes editorial conventions
