Repository tc39/ecma262, pull requests merged in 2023-07, with the labels that each got.

#3102 Editorial: Quick fixes re PR #2418
  spec.html
Labels: editorial change, ready to merge

#3115 Editorial: Fix return-type of TemplateString[s]
  spec.html
Labels: editorial change, spec bug, ready to merge

#3125 Editorial: Correct desiderable to desirable
  spec.html
Labels: editorial change, ready to merge

#3126 Editorial: Correct ExportEntry.[[LocalName]] description
  spec.html
Labels: ready to merge

#3055 Editorial: add mention that RegExp is constructible
  spec.html
Labels: ready to merge

#3092 Editorial: Convert Date-related equations into proper AOs
  spec.html
Labels: editorial change, ready to merge

#3122 Editorial: Prefer returning static values after alias comparison
  spec.html
Labels: editorial change, ready to merge, establishes editorial conventions

#3127 Editorial: Correct GetExportedNames return type
  spec.html
Labels: ready to merge

#3123 Editorial: Eliminate some Date cruft
  spec.html
Labels: editorial change, ready to merge

#3133 Meta: update github actions
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/enforce-format.yml
  .github/workflows/ipr.yml
  .github/workflows/preview-build.yml
  .github/workflows/preview.yml
  .github/workflows/publish-biblio.yml
Labels: meta, ready to merge
