Repository tc39/ecma262, pull requests merged in 2023-05, with the labels that each got.

#3013 Editorial: Consistently represent expressions that include exponents
  spec.html
Labels: editorial change, ready to merge, establishes editorial conventions

#3056 Editorial: In ObjectDefineProperties, use a Record rather than a two-element List
  spec.html
Labels: editorial change, ready to merge

#3051 Editorial: String.prototype.normalize references the Unicode Standard instead of Annex 15
  spec.html
Labels: ready to merge

#3067 Editorial: fix the type of Iterator Record [[NextMethod]]
  spec.html
Labels: editorial change, ready to merge

#3039 Normative: integrate well-formed Unicode strings proposal
  spec.html
Labels: normative change, has test262 tests, proposal, has stage 4, ready to merge

#3058 Editorial: add [[AgentSignifier]] to Realm Record
  spec.html
Labels: editorial change, ready to merge

#3052 Normative: Disallow ArrayBuffers bigger than 2**53
  spec.html
Labels: normative change, has consensus, has test262 tests, ready to merge

#3069 Meta: upgrade ESMeta to v0.3.0
  .github/workflows/esmeta-typecheck.yml
  esmeta-ignore.json
Labels: meta, ready to merge

#2613 Editorial: Define both integer index and array index using inclusive intervals
  spec.html
Labels: editorial change, ready to merge

#3082 [meta] fix newline in snapshot warning
  scripts/insert_snapshot_warning.js
Labels: meta, ready to merge

#3078 Meta: Upgrade ESMeta to v0.3.1
  .github/workflows/esmeta-typecheck.yml
Labels: meta, ready to merge

#3044 Editorial: Simplify CreateArrayIterator
  spec.html
Labels: ready to merge

#3085 Editorial: ToUint8Clamp guard against infinity doubles
  spec.html
Labels: editorial change, spec bug, ready to merge
