Repository tc39/ecma262, pull requests merged in 2023-02, with the labels that each got.

#2780 Editorial: Replace "legal" with more precise language
  spec.html
Labels: ready to merge

#2947 Editorial: For clarity, manipulate _record_.[[Field]] rather than its alias
  spec.html
Labels: editorial change, ready to merge

#3014 Editorial: add emu-not-ref for "date-time values"
  spec.html
Labels: ready to merge

#2436 Normative: allow named backreferences without `u` flag in core grammar
  spec.html
Labels: normative change, has consensus, ready to merge

#2946 Editorial: Clean up the regular expressions section
  spec.html
Labels: editorial change, ready to merge

#3006 Meta: Limit IPR check job to the tc39 repository
  .github/workflows/ipr.yml
Labels: meta, ready to merge

#3017 Editorial: Quick fixes for recent merges
  spec.html
Labels: editorial change, spec bug, ready to merge

#2898 Editorial: Factor out FindViaPredicate
  esmeta-ignore.json
  spec.html
Labels: editorial change, ready to merge

#3016 Editorial: Ensure Abstract Closures don't re-use outer aliases
  spec.html
Labels: editorial change, ready to merge, establishes editorial conventions
