Repository tc39/ecma262, pull requests merged in 2023-06, with the labels that each got.

#3086 Editorial: fix capitalization of "Object type"
  spec.html
Labels: editorial change, ready to merge

#3035 Editorial: simplify and clarify time zone identifier spec text
  esmeta-ignore.json
  spec.html
Labels: editorial change, ready to merge

#3019 Editorial: Replace biblio term "safe" with the more specific "safe integer"
  spec.html
Labels: editorial change, ready to merge

#2994 Editorial: Clarify Proxy.revocable
  spec.html
Labels: editorial change, ready to merge

#3049 Normative: Add Atomics.waitAsync
  spec.html
Labels: normative change, proposal, has stage 4, ready to merge

#3079 Editorial: Simplify ToIndex
  spec.html
Labels: editorial change, ready to merge

#3083 Editorial: Cleanup ToUint8Clamp
  spec.html
Labels: editorial change, ready to merge

#3046 Editorial: Simplify Date(…) and Date.UTC(…)
  spec.html
Labels: editorial change, ready to merge

#3091 Editorial: use standard arithmetic operators in MakeTime
  spec.html
Labels: editorial change, ready to merge

#3100 Meta: Upgrade ESMeta to v0.3.2
  .github/workflows/esmeta-typecheck.yml
Labels: meta, ready to merge

#3066 Editorial: take ToString and ToLength out of StringPad and make it infallible
  esmeta-ignore.json
  spec.html
Labels: editorial change, ready to merge

#3104 Editorial: Remove unnecessary `If` in SystemTimeZoneIdentifier
  spec.html
Labels: ready to merge

#2951 Editorial: Fix 2 old bugs re Block-Level Function Declarations
  spec.html
Labels: editorial change, spec bug, ready to merge

#2982 Editorial: Use linkable terms for coercion to BigInt
  spec.html
Labels: editorial change, ready to merge

#3105 Editorial: rename `~Uint8C~` type to `~Uint8Clamped~`
  spec.html
Labels: editorial change, ready to merge

#3106 Normative: Make `HasCallInTailPosition` for `ImportCall` always return false
  spec.html
Labels: normative change, spec bug, ready to merge
