Repository tc39/ecma262, pull requests merged in 2024-11, with the labels that each got.

#2721 Normative: allow duplicate named capture groups
  spec.html
Labels: normative change, has test262 tests, proposal, has stage 4, ready to merge

#3452 Editorial: Allow ACs in Async{Function,Block}Start
  spec.html
Labels: editorial change, ready to merge

#3454 Editorial: Miscellaneous quick fixes
  spec.html
Labels: editorial change, ready to merge

#3394 Editorial: Assert that Evaluation in JSON.parse does not throw
  spec.html
Labels: editorial change, ready to merge

#3476 Meta: bump ecmarkup to v20.0.0
  package-lock.json
  package.json
  spec.html
Labels: meta, ready to merge

#3477 Editorial: Fix typo
  spec.html
Labels: editorial change, ready to merge

#2924 Editorial: Fixed return types of algorithms returning ~empty~
  esmeta-ignore.json
  spec.html
Labels: editorial change, ready to merge

#3453 Normative: Return false in [[PreventExtensions]] for variable length TypedArrays
  spec.html
Labels: normative change, has consensus, has test262 tests, ready to merge

#3487 Meta: Upgrade ESMeta to v0.5.0
  .github/workflows/esmeta-typecheck.yml
  esmeta-ignore.json
Labels: meta, ready to merge

#3485 Editorial: Add an assertion for PrivateEnvironment cannot be null
  esmeta-ignore.json
  spec.html
Labels: ready to merge
