Repository tc39/ecma262, pull requests merged in 2024-03, with the labels that each got.

#3030 Editorial: Fix `[[DFSIndex]]` in cyclic module record async evaluation example
  spec.html
Labels: editorial change, spec bug, ready to merge

#3293 Editorial: Remove redundant type assertion from AsyncBlockStart
  spec.html
Labels: editorial change, ready to merge

#3290 Editorial: Introduce StringLastIndexOf
  spec.html
Labels: editorial change, ready to merge

#3099 Editorial: Generalize ParseText to support String input
  spec.html
Labels: ready to merge

#3209 Editorial: Introduce IsStrict() abstract operation
  spec.html
Labels: editorial change, ready to merge, establishes editorial conventions

#3271 Editorial: reorganise the mathematical operations section a bit
  spec.html
Labels: editorial change, ready to merge

#3292 Editorial: Remove "message" property from list of Error differences
  spec.html
Labels: editorial change, ready to merge

#3296 Meta: changes for printing
  package-lock.json
  package.json
  spec.html
Labels: meta, ready to merge

#3300 Editorial: make String{,Last}IndexOf return not-found
  spec.html
Labels: ready to merge
