Repository tc39/ecma262, pull requests merged in 2024-01, with the labels that each got.

#3163 Editorial: Use "is a foo completion" instead of testing [[Type]] field
  esmeta-ignore.json
  spec.html
Labels: editorial change, ready to merge, establishes editorial conventions

#3252 Editorial: use the correct type notation for GetSubstitution's captures parameter
  spec.html
Labels: editorial change, ready to merge

#3245 Editorial: avoid using % notation with an alias
  spec.html
Labels: editorial change, ready to merge, establishes editorial conventions

#3255 Normative: Recompute count in TA.p.slice
  spec.html
Labels: normative change, spec bug, ready to merge

#3250 Editorial: document that functions are objects
  spec.html
Labels: editorial change, ready to merge

#3258 Editorial: Improve readability of TypedArray methods
  spec.html
Labels: editorial change, ready to merge

#3257 Editorial: use correct term "current Realm Record" in HostEnqueuePromiseJob
  spec.html
Labels: editorial change, ready to merge

#3203 Editorial: fix formatting of note step in DayFromYear
  spec.html
Labels: editorial change, ready to merge

#3249 Editorial: use _Pk_ for unity of content and form
  spec.html
Labels: editorial change, ready to merge, establishes editorial conventions

#3270 Editorial: move emu-note relating to floor next to definition of floor
  spec.html
Labels: editorial change, ready to merge

#3268 Editorial: Introduce AO combining IteratorStep and IteratorValue
  spec.html
Labels: editorial change, ready to merge

#3275 Editorial: avoid multiple declarations of an alias
  spec.html
Labels: ready to merge

#3273 Editorial: tweak unwrapping of some normal completions
  spec.html
Labels: ready to merge, establishes editorial conventions
