Repository tc39/ecma262, pull requests merged in 2024-10, with the labels that each got.

#3287 Editorial: OrdinaryCreateFromConstructor has wrong parameter type
  esmeta-ignore.json
  spec.html
Labels: editorial change, ready to merge

#3423 Editorial: String.prototype.matchAll iterators won't return null
  spec.html
Labels: editorial change, ready to merge

#3444 Meta: Upgrade ESMeta to v0.4.3
  .github/workflows/esmeta-typecheck.yml
  esmeta-ignore.json
Labels: meta, ready to merge

#3437 Editorial: Narrow return type of CreateBuiltinFunction
  spec.html
Labels: ready to merge

#3395 Normative: add Iterator Helpers
  spec.html
Labels: normative change, proposal, has stage 4, ready to merge

#3407 Editorial: [[HomeObject]] is always an ordinary object
  spec.html
Labels: ready to merge

#3438 Editorial: use suspended-start instead of `undefined` in GeneratorState initialization
  spec.html
Labels: editorial change, ready to merge

#3456 Editorial: Add `Iterator` to global object properties
  spec.html
Labels: editorial change, spec bug, ready to merge

#3458 Editorial: Fix typo in FinalizationRegistry global property link id
  spec.html
Labels: editorial change, ready to merge

#3459 Editorial: fix linking and change spelling of iterator interfaces
  spec.html
Labels: editorial change, ready to merge

#3460 Editorial: eliminate extra verbosity with %GeneratorPrototype% references
  spec.html
Labels: editorial change, ready to merge
