Repository tc39/ecma262, pull requests merged in 2024-08, with the labels that each got.

#3384 Editorial: rename IDs that were embedded in emu-grammar elements back
  spec.html
Labels: ready to merge

#3345 Normative: fully define Math.sqrt
  spec.html
Labels: normative change, has consensus, has test262 tests, ready to merge

#3357 Normative: Fix hangs with top-level await
  spec.html
Labels: normative change, spec bug, has consensus, ready to merge

#3383 Editorial: Initialize [[GeneratorState]] and [[AsyncGeneratorState]]
  spec.html
Labels: ready to merge

#3390 Meta: do not npm audit in CI
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/enforce-format.yml
  .github/workflows/ipr.yml
  .github/workflows/preview-build.yml
  .github/workflows/preview.yml
  .github/workflows/publish-biblio.yml
  .github/workflows/spellcheck.yml
Labels: meta, ready to merge

#3393 Markup: Update broken link in `Number::toString`
  spec.html
Labels: ready to merge, markup

#3400 Editorial: Clamp size before using with "substring of"
  spec.html
Labels: editorial change, spec bug, ready to merge
