Repository tc39/ecma262, pull requests merged in 2025-03, with the labels that each got.

#3353 Editorial: Explicitly track async evaluation order of pending modules
  spec.html
Labels: editorial change, ready to merge

#3547 Editorial: unify NaN phrasing, editorial followups to #3532
  spec.html
Labels: editorial change, ready to merge

#3540 Editorial: Extract JSON parsing into its own AO
  spec.html
Labels: editorial change, ready to merge

#3549 Markup: consistent spacing for method signatures in tables
  spec.html
Labels: ready to merge

#3541 Editorial: Put module concrete methods in their own emu-clauses
  spec.html
Labels: editorial change, ready to merge

#3550 Markup: Print styles for slashed corner cell
  spec.html
Labels: ready to merge, markup

#3553 Meta: bump ecmarkup to v21.2.0
  package-lock.json
  package.json
Labels: meta, ready to merge

#3554 Markup: more slashed corner cells
  spec.html
Labels: ready to merge
