Repository tc39/ecma262, pull requests merged in 2025-08, with the labels that each got.

#3644 Editorial: allow Symbols and Private Names to have internals slots and use slot notation as appropriate
  spec.html
Labels: editorial change, ready to merge

#3654 Normative: add Math.sumPrecise
  spec.html
Labels: normative change, has test262 tests, proposal, has stage 4, ready to merge

#3675 Editorial: add note to SetFunctionName clarifying optionality
  spec.html
Labels: editorial change, ready to merge

#3678 Meta: remove unused pagedjs dependencies
  package-lock.json
  package.json
Labels: meta, ready to merge

#3681 Editorial: remove unnecessary pluralization
  spec.html
Labels: ready to merge

#2840 Normative: Set [[SourceText]] on classes before static blocks evaluate
  spec.html
Labels: normative change, web reality, ready to merge

#3623 Markup: rendering edits for 2025 edition & beyond
  spec.html
Labels: ready to merge, markup

#3676 Editorial: make RequireObjectCoercible return `~unused~`
  spec.html
Labels: editorial change, ready to merge
