Repository tc39/ecma262, pull requests merged in 2025-06, with the labels that each got.

#3616 Meta: Add WebAssembly to our list of downstream dependencies
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: meta, ready to merge

#3507 Normative: add `Error.isError`
  spec.html
Labels: normative change, has test262 tests, proposal, has stage 4, ready to merge

#3429 Editorial: List all TypedArray internal slots
  spec.html
Labels: ready to merge

#3599 Editorial: mark a callsite of GetBindingValue as not throwing
  spec.html
Labels: ready to merge

#3607 Editorial: FunctionDeclarationInstantiation cannot return ReturnCompletion
  esmeta-ignore.json
  spec.html
Labels: editorial change, ready to merge

#3614 Meta: Upgrade ESMeta to v0.6.1
  .github/workflows/esmeta-typecheck.yml
Labels: meta, ready to merge

#3632 Editorial: Reorder some TypedArray AOs to support top-down readability and future refactoring
  spec.html
Labels: ready to merge
