Repository tc39/ecma262, pull requests merged in 2025-09, with the labels that each got.

#3679 Meta: fix PR previews
  .github/workflows/pr-preview.yml
  .github/workflows/preview-build.yml
  .github/workflows/preview.yml
  package-lock.json
  package.json
  scripts/auto-deploy.sh
  scripts/publish-preview.js
Labels: meta, ready to merge

#3595 Editorial: Unify style of abrupt completion and non-LoopContinues result handling in ForIn/OfBodyEvaluation
  spec.html
Labels: editorial change, ready to merge

#3608 Editorial: replace "is at least" with ≥ in parseInt
  spec.html
Labels: editorial change, ready to merge

#3619 Normative: When TA.copyWithin argument handling shrinks TA, use whatever elements still fit
  spec.html
Labels: normative change, web reality, has consensus, has test262 tests, ready to merge

#3620 Editorial: Make "Properties of the Iterator Prototype Object" a subclause of "Iterator Objects"
  spec.html
Labels: editorial change, ready to merge

#3693 Meta: bump ecmarkup to v21.4.0
  package-lock.json
  package.json
Labels: meta, ready to merge
