Repository tc39/ecma262, pull requests merged in 2025-02, with the labels that each got.

#3506 Meta: update upload-artifact action prior to deprecation
  .github/workflows/preview-build.yml
  .github/workflows/preview.yml
Labels: meta, ready to merge

#3381 Editorial: make single-implementation concrete methods into abstract operations
  spec.html
Labels: ready to merge

#3411 Editorial: simplify AsyncGeneratorDrainQueue
  spec.html
Labels: editorial change, ready to merge

#3469 Editorial: Consistify capitalization re iterator wording
  spec.html
Labels: editorial change, ready to merge

#3531 Editorial: Store ToString(𝔽(k)) in a variable for consistency
  spec.html
Labels: editorial change, ready to merge

#3057 Normative: Add Import Attributes
  esmeta-ignore.json
  spec.html
Labels: normative change, has test262 tests, proposal, has stage 4, ready to merge

#3391 Normative: Add JSON modules
  spec.html
Labels: normative change, has test262 tests, proposal, has stage 4, ready to merge

#3536 Editorial: Fix typos and phrasing in slot descriptions
  spec.html
Labels: ready to merge

#2600 Normative: Close sync iterator when async wrapper yields rejection
  spec.html
Labels: normative change, has consensus, has test262 tests, ready to merge

#3226 Normative: Remove [[VarNames]] from the global
  spec.html
Labels: normative change, has test262 tests, has stage 4, ready to merge

#3382 Normative: add `RegExp.escape`
  spec.html
Labels: normative change, has test262 tests, proposal, has stage 4, ready to merge

#3467 Normative: iterator helpers close receiver on argument validation failure
  spec.html
Labels: normative change, has consensus, has test262 tests, ready to merge

#3532 Normative: add Float16Array and Math.f16round
  spec.html
Labels: normative change, has test262 tests, proposal, has stage 4, ready to merge

#3537 Editorial: Document initial internal slot values at their point of creation
  spec.html
Labels: ready to merge

#3546 Editorial: Change remaining `_c_` to `_cp_` in EncodeForRegExpEscape
  spec.html
Labels: ready to merge
