Repository tc39/ecma262, pull requests merged in 2025-04, with the labels that each got.

#3402 Editorial: Remove unnecessary `undefined` type from property descriptor tests
  spec.html
Labels: ready to merge

#3558 Editorial: address circular definition of Iterator.prototype
  spec.html
Labels: editorial change, ready to merge

#3559 Normative: Revert ArrayIterator and RegExpStringIterator to manual iterators
  spec.html
Labels: normative change, spec bug, ready to merge

#3560 Meta: remove Twitter link for me
  spec.html
Labels: meta, ready to merge

#3561 Meta: replace Twitter link with Bluesky for me
  spec.html
Labels: meta, ready to merge

#3562 Meta: remove Twitter link for bakkot
  spec.html
Labels: meta, ready to merge

#3566 Editorial: Quick fixes re recent merge
  spec.html
Labels: editorial change, ready to merge

#3070 Editorial: Fix some ?! misuses
  spec.html
Labels: editorial change, spec bug, ready to merge

#3573 Meta: Upgrade ESMeta to v0.6.0
  .github/workflows/esmeta-typecheck.yml
Labels: meta, ready to merge
