Repository tc39/ecma262, pull requests merged in 2025-07, with the labels that each got.

#3568 Normative: Add "Runtime Errors for Function Call Assignment Targets" to Annex B
  spec.html
Labels: normative change, web reality, has consensus, has test262 tests, ready to merge

#3601 Editorial: wrap AC return values in completion records where needed
  spec.html
Labels: editorial change, completion records, ready to merge

#3638 Normative: WeakRef.prototype.constructor should be writable
  spec.html
Labels: ready to merge

#3641 Editorial: Refer to [[Call]] as an internal method
  spec.html
Labels: editorial change, ready to merge

#3642 Editorial: Include "object" in dfn for WeakRef and FinalizationRegistry prototype object
  spec.html
Labels: ready to merge

#3647 Editorial: consistently order undefined before null in comparisons
  spec.html
Labels: editorial change, ready to merge, establishes editorial conventions

#3656 Meta: Upgrade ESMeta to v0.6.4
  .github/workflows/esmeta-typecheck.yml
Labels: meta, ready to merge

#3653 Editorial: unify various forms of if-otherwise in single-line conditionals
  spec.html
Labels: editorial change, ready to merge
