Repository tc39/ecma262, pull requests merged in 2025-01, with the labels that each got.

#3457 Editorial: fix IteratorClose call in %IteratorHelperPrototype%.return
  spec.html
Labels: spec bug, ready to merge

#3490 Editorial: clarify that Map/Set do not literally use SameValueZero
  spec.html
Labels: ready to merge

#3491 Editorial: more explicit handling of [[PromiseResult]]
  spec.html
Labels: ready to merge

#3503 Editorial: two minor tweaks to the RegExp machinery
  spec.html
Labels: ready to merge

#3511 Editorial: Don't set [[GlobalEnv]] to undefined temporarily
  spec.html
Labels: ready to merge

#3221 Normative: Add RegExp Modifiers
  spec.html
Labels: normative change, has test262 tests, proposal, has stage 4, ready to merge

#3466 Editorial: Narrowing an assertion in SuperCall: super Arguments
  esmeta-ignore.json
  spec.html
Labels: editorial change, ready to merge

#3488 Editorial: Add [[ImportName]] assertion for non-direct binding cases in ResolveExports
  esmeta-ignore.json
  spec.html
Labels: editorial change, ready to merge

#3495 Editorial: Allocate-and-use in MakeMatchIndicesIndexPairArray for refinement
  esmeta-ignore.json
  spec.html
Labels: editorial change, ready to merge

#3379 Editorial: Add assertion that generatorKind is not non-generator
  esmeta-ignore.json
  spec.html
Labels: editorial change, ready to merge

#3525 Editorial: consistency around how we refer to GlobalSymbolRegistry stuff
  spec.html
Labels: editorial change, ready to merge
